### ISSUE TITLE
v3 version a question

### ISSUE THREAD

**Issue by giserman001** [nativescript-vue/nativescript-vue#1056]
System.err: TypeError: Class constructor TabView cannot be invoked without 'new'
  System.err:   at com.tns.Runtime.runModule(Native Method)
  System.err:   at com.tns.Runtime.runModule(Runtime.java:689)
  System.err:   at com.tns.Runtime.run(Runtime.java:681)
  System.err:   at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
  System.err:   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1191)
  System.err:   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6987)

**Comment by heywhy** [comment]
This issue is fixed by #1064

**Comment by PixsaOJ** [comment]
Why is this open?
