### ISSUE TITLE
Command failed: ruby -e "require 'xcodeproj'

### ISSUE THREAD

**Issue by jarrodwhitley** [nativescript-vue/nativescript-vue#1070]
## Platform and OS info
Apple M1 / macOS 12.7.1 / NativeScript 8.6.1 / Nativescript-vue 2.9.0

## What is expected?
I expect "ns build ios" to complete successfully.

## What is actually happening?
I'm getting an error.

**Note:** Since this is a build issue I can't provide a reproduction and since this is a private company repo I can't provide a link to the code. I'm hoping there may be some troubleshooting steps I can take that won't require either of those.

## Steps to reproduce
From project directory run `ns doctor ios` which outputs:

```
No issues were detected.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 14.2.0 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.6.1 version and is up to date.
⚠ Update available for component @nativescript/core. Your current version is 8.4.7 and the latest available version is 8.6.1.
⚠ Update available for component @nativescript/ios. Your current version is 8.4.1 and the latest available version is 8.6.3.
```
Run `ns build ios`. Error is returned:
```
Command failed: ruby -e "require 'xcodeproj';
		userConfig = Xcodeproj::Config.new('/Users/jwhitley/Code/myhighland-app/platforms/ios/plugins-debug.xcconfig')
		existingConfig = Xcodeproj::Config.new('/Users/jwhitley/Code/myhighland-app/App_Resources/iOS/build.xcconfig')
		userConfig.attributes.each do |key,|
  			existingConfig.attributes.delete(key) if (userConfig.attributes.key?(key) && existingConfig.attributes.key?(key))
		end
		userConfig.merge(existingConfig).save_as(Pathname.new('/Users/jwhitley/Code/myhighland-app/platforms/ios/plugins-debug.xcconfig'))"
/Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:86:in `require': cannot load such file -- xcodeproj (LoadError)
	from /Library/Ruby/Site/2.6.0/rubygems/core_ext/kernel_require.rb:86:in `require'
	from -e:1:in `<main>'
	
```

## Troubleshooting
I've tried googling different parts of this error, but I'm not discovering any solutions. The only thing I've found that is similar is [this post](https://github.com/ProgressNS/sidekick-feedback/issues/179) where the user explains that he solved the problem by fixing a "Ruby install conflict". He said he updated Ruby and cocoapods (re-installed) and it "started working". 

I thought I'd give it a shot so I ran `brew upgrade ruby` and only got more confused.

```
➜  myhighland-app git:(feature/v1.0.10-jarrod) ✗ brew upgrade ruby
==> Downloading https://formulae.brew.sh/api/formula.jws.json
################################################################################################################################# 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
################################################################################################################################# 100.0%
Warning: ruby 3.2.2_1 already installed
➜  myhighland-app git:(feature/v1.0.10-jarrod) ✗ ruby --version
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin21]
```

So I'm not even sure what version of Ruby I'm on, but I also re-installed cocoapods successfully and still get the same error. I'm not sure what the next step should be. Any help would be appreciated.

This is my `package.json` file:

```
  "dependencies": {
    "@nativescript/apple-sign-in": "^1.0.0",
    "@nativescript/background-http": "^6.0.0",
    "@nativescript/core": "8.4",
    "@nativescript/facebook": "~2.1.0",
    "@nativescript/firebase-analytics": "https://gitpkg.now.sh/meganedesigns/firebase/packages/firebase-analytics?2.0.1b",
    "@nativescript/firebase-core": "https://gitpkg.now.sh/meganedesigns/firebase/packages/firebase-core?2.0.1b",
    "@nativescript/firebase-messaging": "https://gitpkg.now.sh/meganedesigns/firebase/packages/firebase-messaging?2.0.1b",
    "@nativescript/google-signin": "^1.0.0",
    "@nativescript/imagepicker": "^1.0.6",
    "@nativescript/local-notifications": "^6.0.0",
    "@nativescript/theme": "~3.0.1",
    "@triniwiz/nativescript-socketio": "^4.0.1",
    "@triniwiz/nativescript-toasty": "^4.1.3",
    "assert": "^2.0.0",
    "axios": "^0.24.0",
    "browserify-zlib": "^0.2.0",
    "buffer": "^6.0.3",
    "facebookgraph": "^0.4.0",
    "highlight-words-core": "^1.2.2",
    "https-browserify": "^1.0.0",
    "nativescript-appversion": "github:imandyie/nativescript-appversion",
    "nativescript-fonticon": "^2.0.2",
    "nativescript-gif": "^5.0.0",
    "nativescript-phone": "^3.0.2",
    "nativescript-ui-listview": "^10.0.2",
    "nativescript-vue": "~2.9.0",
    "nativescript-vue-template-compiler": "~2.9.0",
    "os-browserify": "^0.3.0",
    "path": "^0.12.7",
    "platform": "^1.3.6",
    "rxjs": "^7.5.5",
    "sass": "^1.32.8",
    "stream-browserify": "^3.0.0",
    "stream-http": "^3.2.0",
    "tty-browserify": "0.0.1",
    "url": "^0.11.0",
    "util": "^0.12.4",
    "v-mask": "^2.3.0",
    "vue-axios": "^3.4.0",
    "vuex": "^3.6.2"
  },
  "devDependencies": {
    "@nativescript/android": "8.4",
    "@nativescript/ios": "8.4",
    "@nativescript/webpack": "~5.0.0",
    "@vue/devtools": "^5.3.4",
    "nativescript-vue-devtools": "^1.5.1"
  }
```

**Comment by jarrodwhitley** [comment]
Running `brew gem install xcodeproj —user-install` fixed the issue for me.
