### ISSUE TITLE
Error duplicate resources 

### ISSUE THREAD

**Issue by defaultbr** [nativescript-vue/nativescript-vue#117]
Hi, im trying to use firebase/vuefire but when i install it (just the installation) the application stop compiling:

```
➜  teste_native_script_2 tns run android                            
Searching for devices...
Executing before-prepare hook from /home/tarcisio/TesteNativeScript/teste_native_script_2/hooks/before-prepare/nativescript-plugin-firebase.js
Preparing project...
Successfully prepared plugin nativescript-plugin-firebase for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin nativescript-vue for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (Android)
Executing after-prepare hook from /home/tarcisio/TesteNativeScript/teste_native_script_2/hooks/after-prepare/firebase-build-gradle.js
Configure firebase
Executing after-prepare hook from /home/tarcisio/TesteNativeScript/teste_native_script_2/hooks/after-prepare/firebase-copy-google-services.js
Copy /home/tarcisio/TesteNativeScript/teste_native_script_2/app/App_Resources/Android/google-services.json to /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/google-services.json.
Executing after-prepare hook from /home/tarcisio/TesteNativeScript/teste_native_script_2/hooks/after-prepare/nativescript-plugin-firebase.js
Building project...
Gradle build...
         + applying user-defined configuration from /home/tarcisio/TesteNativeScript/teste_native_script_2/app/App_Resources/Android/app.gradle
         + add include.gradle from /home/tarcisio/TesteNativeScript/teste_native_script_2/node_modules/nativescript-plugin-firebase/platforms/android/include.gradle
         + applying plugin configuration from /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/build/configurations/nativescript-plugin-firebase/include.gradle
         + adding nativescript runtime package dependency: nativescript-optimized
         + adding aar plugin dependency: /home/tarcisio/TesteNativeScript/teste_native_script_2/node_modules/nativescript-plugin-firebase/platforms/android/firebase-release.aar
         + adding aar plugin dependency: /home/tarcisio/TesteNativeScript/teste_native_script_2/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
false
Running full build
Could not merge source set folders: 
[app/tns_modules/long/dist/long.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/long/dist/long.min.js.gz    [app/tns_modules/long/dist/long.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/long/dist/long.min.js: Error: Duplicate resources
[app/tns_modules/protobufjs/dist/protobuf.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf.min.js.gz        [app/tns_modules/protobufjs/dist/protobuf.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf.min.js: Error: Duplicate resources
[app/tns_modules/protobufjs/dist/protobuf-light.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf-light.min.js.gz    [app/tns_modules/protobufjs/dist/protobuf-light.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf-light.min.js: Error: Duplicate resources
[app/tns_modules/bytebuffer/dist/bytebuffer.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer.min.js.gz    [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer.min.js: Error: Duplicate resources
[app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js     [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js.gz: Error: Duplicate resources
        at com.android.ide.common.res2.DataSet.checkItems(DataSet.java:466)
        at com.android.ide.common.res2.DataSet.loadFromFiles(DataSet.java:258)
        at com.android.ide.common.res2.AssetSet.loadFromFiles(AssetSet.java:30)
        at com.android.build.gradle.tasks.MergeSourceSetFolders.doFullTaskAction(MergeSourceSetFolders.java:104)
        at com.android.build.gradle.tasks.MergeSourceSetFolders.doIncrementalTaskAction(MergeSourceSetFolders.java:157)
        at com.android.build.gradle.internal.tasks.IncrementalTask.taskAction(IncrementalTask.java:108)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeF0DebugAssets'.
> [app/tns_modules/long/dist/long.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/long/dist/long.min.js.gz  [app/tns_modules/long/dist/long.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/long/dist/long.min.js: Error: Duplicate resources
  [app/tns_modules/protobufjs/dist/protobuf.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf.min.js.gz      [app/tns_modules/protobufjs/dist/protobuf.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf.min.js: Error: Duplicate resources
  [app/tns_modules/protobufjs/dist/protobuf-light.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf-light.min.js.gz  [app/tns_modules/protobufjs/dist/protobuf-light.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/protobufjs/dist/protobuf-light.min.js: Error: Duplicate resources
  [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer.min.js.gz  [app/tns_modules/bytebuffer/dist/bytebuffer.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer.min.js: Error: Duplicate resources
  [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js   [app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js] /home/tarcisio/TesteNativeScript/teste_native_script_2/platforms/android/app/src/main/assets/app/tns_modules/bytebuffer/dist/bytebuffer-dataview.min.js.gz: Error: Duplicate resources

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Unable to apply changes on device: 0029853750. Error is: Command ./gradlew failed with exit code 1
```

github vurefire -> https://github.com/vuejs/vuefire

is possible to use another packages with it or vuefire should be changed to work with nativescript-vue?

## steps to reproduce:

1) Install default nativescript-vue template
2) Install dependencies:
```npm install vue firebase vuefire --save```

**Comment by rigor789** [comment]
for firebase you will have to use the nativescript specific version https://market.nativescript.org/plugins/nativescript-plugin-firebase
