### ISSUE TITLE
TypeError: Cannot read property 'getKeyedTemplates' of undefined

### ISSUE THREAD

**Issue by kapany3** [nativescript-vue/nativescript-vue#120]
Hi. I got this error after start demo app with app-with-list-view.js

```
tns run android
Searching for devices...
Skipping prepare.
Refreshing application...
Successfully synced application org.nativescript.vuetmpl on device emulator-5554.
ActivityManager: Start proc 4165:org.nativescript.vuetmpl/u0a16 for activity org.nativescript.vuetmpl/com.tns.NativeScriptActivity
JS: 'NativeScript-Vue has "Vue.config.silent" set to true, to see output logs set it to false.'
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.vuetmpl/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'getKeyedTemplates' of undefined
System.err: File: "file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js, line: 2137, column: 6
System.err: StackTrace: 
System.err:     Frame: function:'mounted', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 10335, column: 22
System.err:     Frame: function:'callHook', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3217, column: 21
System.err:     Frame: function:'insert', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 9225, column: 7
System.err:     Frame: function:'invokeInsertHook', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3777, column: 28
System.err:     Frame: function:'patch', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3996, column: 5
System.err:     Frame: function:'Vue._update', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2959, column: 19
System.err:     Frame: function:'updateComponent', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3087, column: 10
System.err:     Frame: function:'get', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2132, column: 25
System.err:     Frame: function:'Watcher', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2121, column: 12
System.err:     Frame: function:'mountComponent', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3094, column: 3
System.err:     Frame: function:'create', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 10544, column: 9
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 51, column: 22
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 101, column: 16
System.err:     Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:148)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: TypeError: Cannot read property 'getKeyedTemplates' of undefined
System.err: File: "file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js, line: 2137, column: 6
System.err: StackTrace: 
System.err:     Frame: function:'mounted', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 10335, column: 22
System.err:     Frame: function:'callHook', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3217, column: 21
System.err:     Frame: function:'insert', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 9225, column: 7
System.err:     Frame: function:'invokeInsertHook', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3777, column: 28
System.err:     Frame: function:'patch', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3996, column: 5
System.err:     Frame: function:'Vue._update', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2959, column: 19
System.err:     Frame: function:'updateComponent', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3087, column: 10
System.err:     Frame: function:'get', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2132, column: 25
System.err:     Frame: function:'Watcher', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 2121, column: 12
System.err:     Frame: function:'mountComponent', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 3094, column: 3
System.err:     Frame: function:'create', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/nativescript-vue/dist/index.js', line: 10544, column: 9
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 51, column: 22
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 101, column: 16
System.err:     Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
System.err:     Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
System.err:     Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.vuetmpl/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
System.err:     at android.app.Activity.performCreate(Activity.java:6237)
System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
System.err:     ... 9 more
ActivityManager: Process org.nativescript.vuetmpl (pid 4165) has died
```

**Comment by rigor789** [comment]
Hi, I've started updating this sample, and ran into a little issue that I have to solve. I'll update the sample in a bit. Thanks for the heads up!

**Comment by rigor789** [comment]
Should be fixed now!
