### ISSUE TITLE
can't use the `nativescript-pdf-view` plugin?

### ISSUE THREAD

**Issue by jarden-liu** [nativescript-vue/nativescript-vue#160]
At first, I install PDF plugin by npm,
```bash
   npm install --save nativescript-pdf-view
```
Then register element in `main.js`
```javascript
   Vue.registerElement('PDFView', () => require('nativescript-pdf-view').PDFView);
```
But after I added the `PDFView` element  into my page template, I got an error exception.
```html
 <Page class="page">
    <ActionBar class="action-bar" title="home"> </ActionBar>
    <StackLayout>
      <Label text="hello"></Label>
      <PDFView src="https://cdn.mozilla.net/pdfjs/tracemonkey.pdf"></PDFView>
    </StackLayout>
  </Page>
```

The exception as follow:
```
 An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.edu.sustc.xh.meeting/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: A Frame must be used to navigate to a Page.
File: "file:///data/data/cn.edu.sustc.xh.meeting/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 605, column: 16

StackTrace: 
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/cn.edu.sustc.xh.meeting/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 605, column: 23
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/cn.edu.sustc.xh.meeting/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2319)
	at android.app.ActivityThread.access$1100(ActivityThread.java:141)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5342)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:871)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: A Frame must be used to navigate to a Page.
File: "file:///data/data/cn.edu.sustc.xh.meeting/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 605, column: 16

StackTrace: 
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/cn.edu.sustc.xh.meeting/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 605, column: 23
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/cn.edu.sustc.xh.meeting/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:5354)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1090)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2234)
	... 11 more

```

**Comment by rigor789** [comment]
Did you run `npm run clean` after you have installed this plugin?

Are you using page routing?

**Comment by jarden-liu** [comment]
yea, i using vue-router!

**Comment by rigor789** [comment]
This is most likely a router related issue, which is experimental. For now your best option is to try without the router

**Comment by happones** [comment]
try your example, and I worked with vue-router, what I did was to remove the android platform and reinstall it with some plugins this step is necessary, and additionally remove the <StackLayout> and <Label> tags only leave <PDFView / >, I hope it serves you

`<Page class="page">
            <ActionBar class="action-bar" title="home"> </ActionBar>
            <PDFView src="https://cdn.mozilla.net/pdfjs/tracemonkey.pdf"></PDFView>
          </Page>
`

**Comment by jarden-liu** [comment]
Really?? i will try it later.  Thanks

**Comment by altunyurt** [comment]
That is most probably caused by 
    
    pageRouting: true

in vue-router settings. Try commenting it out and use component based routing.

        const AppMain = {
        template: `
        <Page class="page" actionBarHidden="true" ref="page">
                ...
                <transition name="fade" :duration="1000" mode="out-in">
                    <router-view />
                </transition>
                ...
        </Page>

        `
    }

    const Home = {
        template: `
        <StackLayout>
            <Label text="hey!" />
        </StackLayout>
    `
    }

    var router = new VueRouter({
        routes: [
                { path: '/home', component: Home, name: 'home', meta: { title: 'Home' } },
        ]
    });
    router.replace('/home');

    new Vue({
        router: router,
        store: store,
        components: {AppMain},
        template: `<AppMain> </AppMain>`,
    }).$start()

**Comment by rigor789** [comment]
Works on v2.
