### ISSUE TITLE
Cannot run a built app (sometimes) 

### ISSUE THREAD

**Issue by wrbl606** [nativescript-vue/nativescript-vue#182]
Sometimes app gives an error below, even though everything is ok with JavaScript code.

Stack trace:
```Java
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "../application", relative to: app/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5512)
    android.app.ActivityThread.-wrap2(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6247)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 142162
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 141928
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 136038
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 135536
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 2029
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 521
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "../application", relative to: app/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5512)
    android.app.ActivityThread.-wrap2(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6247)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 142162
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 141928
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 136038
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 135536
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 2029
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 521
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5515)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6247)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

Error: com.tns.NativeScriptException: Failed to find module: "../application", relative to: app/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5512)
    android.app.ActivityThread.-wrap2(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6247)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 142162
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 141928
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 136038
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 135536
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 2029
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 521
	Frame: function:'require', file:'', line: 1, column: 266


Error: com.tns.NativeScriptException: Failed to find module: "../application", relative to: app/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.runModule(Native Method)
    com.tns.Runtime.runModule(Runtime.java:530)
    com.tns.Runtime.run(Runtime.java:522)
    com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
    android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
    android.app.ActivityThread.handleBindApplication(ActivityThread.java:5512)
    android.app.ActivityThread.-wrap2(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6247)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 142162
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 141928
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 136038
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'Object.defineProperty.value', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 135536
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 2029
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 161
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 511
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 521
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:530)
	at com.tns.Runtime.run(Runtime.java:522)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5512)
	... 8 more
```

**Comment by wrbl606** [comment]
I think it is worth to mention: I've once fixed the issue by cleaning */dist* folder and uninstalling the app from test device.

Unfortunately it isn't help everytime - maybe I'm missing some cleaning step.

**Comment by mehyaa** [comment]
I've these kind of errors too. It is because the module that has the require statement marked as external but the statement is not fixed to that has to be. [This fix](https://github.com/nativescript-vue/nativescript-vue-externals/pull/4) should fix it.

**Comment by wrbl606** [comment]
Thanks. It's working correctly now 😀
