### ISSUE TITLE
App crash on router back with pageRouting navigation

### ISSUE THREAD

**Issue by academici** [nativescript-vue/nativescript-vue#203]
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method run failed

TypeError: Cannot read property '__ob__' of undefined
File: "file:///data/data/org.nativescript.application/files/app/app.js, line: 6878, column: 16

StackTrace: 
	Frame: function:'Vue.$destroy', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 6878, column: 17
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 16698, column: 26
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 9856, column: 10
	Frame: function:'ViewBase._tearDownUI', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 564, column: 14
	Frame: function:'ViewBase._removeViewCore', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 464, column: 18
	Frame: function:'ViewBase._removeView', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js', line: 457, column: 14
	Frame: function:'FrameBase._removeEntry', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 107, column: 19
	Frame: function:'Frame._removeEntry', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 262, column: 39
	Frame: function:'FrameBase._updateBackstack', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 165, column: 18
	Frame: function:'Frame.setCurrent', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 173, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/fragment.transitions.js', line: 562, column: 53
	Frame: function:'invoke', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
	Frame: function:'run', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by academici** [comment]
I use nativescript 4.0, nativescript-vue 1.3.1

**Comment by rigor789** [comment]
Closing due to inactivity.

**Comment by Fabiyo-90** [comment]
I have the same bug
