### ISSUE TITLE
NativeScript Plugins don't work

### ISSUE THREAD

**Issue by Xstyler85** [nativescript-vue/nativescript-vue#223]
I create new project with the vue-cli. I install vue router and vuex.

Then I fallow [this ](https://nativescript-vue.org/en/docs/getting-started/nativescript-plugins/) steps how to install nativescript gradient plugin and I got this error in emulator:

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.application/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: A Frame must be used to navigate to a Page.
File: "file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 605, column: 16

StackTrace: 
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 605, column: 23
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

Error: A Frame must be used to navigate to a Page.
File: "file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 605, column: 16

StackTrace: 
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 605, column: 23
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6679)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
	... 9 more
```

**Comment by MisterBrownRSA** [comment]
Can you share more information, maybe your template code ?

**Comment by Xstyler85** [comment]
I made a fresh install: 
1. vue init nativescript-vue/vue-cli-template native-app
2. cd native-app
3. npm install
4. npm install --save nativescript-gradient
5. npm run clean
6. I add "Vue.registerElement('Gradient', () => require('nativescript-gradient').Gradient)" in mian.js
7. Then I add "Gradient" in Home.vue:
```
<Gradient direction="to right" colors="#FF0077, red, #FF00FF">
  <Label text="Best gradient." horizontalAlignment="center"
         style="color: white; padding: 20" />
</Gradient>
```
8. npm run watch:android

Then I got error.

My home looks like this:
```
<template>
  <Page class="page">
    <Gradient direction="to right" colors="#FF0077, red, #FF00FF">
      <Label text="Best gradient." horizontalAlignment="center"
             style="color: white; padding: 20" />
    </Gradient>
  </Page>
</template>

```

**Comment by MisterBrownRSA** [comment]
Gradient can't be your root element after Page, try placing it in a `StackLayout` or `FlexboxLayout`

**Comment by Xstyler85** [comment]
Currently, I'm on the Windows 10, but I have the same problem at home on Windows 8.1

package.json

```
{
  "name": "native-app",
  "version": "1.0.0",
  "description": "A native application built with NativeScript-Vue",
  "author": "Elvis Kravos",
  "license": "MIT",
  "scripts": {
    "build": "webpack --env.tnsAction build",
    "build:android": "npm run build -- --env.android",
    "build:ios": "npm run build -- --env.ios",
    "debug": "webpack --watch --env.tnsAction debug",
    "debug:android": "npm run debug -- --env.android",
    "debug:ios": "npm run debug -- --env.ios",
    "watch": "webpack --watch --env.tnsAction run",
    "watch:android": "npm run watch -- --env.android",
    "watch:ios": "npm run watch -- --env.ios",
    "clean": "rimraf dist"
  },
  "dependencies": {
    "nativescript-gradient": "^2.0.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-vue": "^1.3.1",
    "tns-core-modules": "~3.4.1",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^3.0.2",
    "fs-extra": "^5.0.0",
    "nativescript-vue-externals": "^0.1.2",
    "nativescript-vue-loader": "^0.1.5",
    "nativescript-vue-target": "^0.1.0",
    "nativescript-vue-template-compiler": "^1.3.1",
    "node-sass": "^4.7.2",
    "ns-vue-loader": "^0.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "rimraf": "^2.6.2",
    "sass-loader": "^6.0.7",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^3.11.0",
    "webpack-synchronizable-shell-plugin": "0.0.7",
    "winston-color": "^1.0.0"
  }
}
```

**Comment by Xstyler85** [comment]
I got differant error now:

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.application/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Could not load view for: gradient. Error: com.tns.NativeScriptException: Failed to find module: "nativescript-gradient\gradient-common", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6679)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
    android.app.ActivityThread.-wrap12(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6119)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
File: "file:///data/data/org.nativescript.application/files/app/app.js, line: 1, column: 78636

StackTrace: 
	Frame: function:'Et', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 24595
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 91671
	Frame: function:'t.createElement', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 93093
	Frame: function:'an', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 27053
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94418
	Frame: function:'m', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 95316
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94442
	Frame: function:'e.nodeOps', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 99574
	Frame: function:'e._update', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 108675
	Frame: function:'r', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16143
	Frame: function:'ms.get', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78604
	Frame: function:'ms', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78527
	Frame: function:'qe', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16167
	Frame: function:'xl', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 118472
	Frame: function:'Qo.$mount', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 118769
	Frame: function:'init', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 105771
	Frame: function:'l', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94712
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94147
	Frame: function:'e.nodeOps', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 100060
	Frame: function:'e._update', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 108675
	Frame: function:'r', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16143
	Frame: function:'ms.get', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78604
	Frame: function:'ms', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78527
	Frame: function:'qe', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16167
	Frame: function:'create', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 118324
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 51, column: 22
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 101, column: 16
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Could not load view for: gradient. Error: com.tns.NativeScriptException: Failed to find module: "nativescript-gradient\gradient-common", relative to: app/tns_modules/
    com.tns.Module.resolvePathHelper(Module.java:146)
    com.tns.Module.resolvePath(Module.java:55)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
    android.app.Activity.performCreate(Activity.java:6679)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
    android.app.ActivityThread.-wrap12(ActivityThread.java)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:154)
    android.app.ActivityThread.main(ActivityThread.java:6119)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
File: "file:///data/data/org.nativescript.application/files/app/app.js, line: 1, column: 78636

StackTrace: 
	Frame: function:'Et', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 24595
	Frame: function:'t', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 91671
	Frame: function:'t.createElement', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 93093
	Frame: function:'an', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 27053
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94418
	Frame: function:'m', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 95316
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94442
	Frame: function:'e.nodeOps', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 99574
	Frame: function:'e._update', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 108675
	Frame: function:'r', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16143
	Frame: function:'ms.get', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78604
	Frame: function:'ms', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78527
	Frame: function:'qe', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16167
	Frame: function:'xl', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 118472
	Frame: function:'Qo.$mount', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 118769
	Frame: function:'init', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 105771
	Frame: function:'l', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94712
	Frame: function:'u', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 94147
	Frame: function:'e.nodeOps', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 100060
	Frame: function:'e._update', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 108675
	Frame: function:'r', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16143
	Frame: function:'ms.get', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78604
	Frame: function:'ms', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 78527
	Frame: function:'qe', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 16167
	Frame: function:'create', file:'file:///data/data/org.nativescript.application/files/app/app.js', line: 1, column: 118324
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 51, column: 22
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 101, column: 16
	Frame: function:'FrameBase.navigate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 213, column: 28
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 615, column: 19
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6679)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
	... 9 more
```

**Comment by Xstyler85** [comment]
If you are a Windows user, here is the hot fix by MisterBrownRSA:

go to your `webpack.config.js` and find `externals: NativescriptVuewExternals` and replace it with this:
```
externals: (context, request, callback) => {

            if (context.indexOf('tns-core-modules') !== -1 ||
                context.indexOf('nativescript-') !== -1 ||
                /^(tns-core-modules)/i.test(request) ||
                /^(ui|application)/i.test(request)) {

                // Support plugins requiring sibling files by rewriting './' into 'context/'
                if (request.indexOf('./') === 0) {
                    request = path.join(path.basename(context), request.substring(2));
                }

                request = request.replace(/\\/g, '/');

                return callback(null, 'commonjs ' + request);
            }

            request = request.replace(/\\/g, '/');

            callback();
        },
```

**Comment by rigor789** [comment]
Closing this because as @brunokunace said, the new version of nativescirpt-vue-externals should fix the issue.
