### ISSUE TITLE
Installation breaks after a few hours

### ISSUE THREAD

**Issue by wendt88** [nativescript-vue/nativescript-vue#343]
### Version
2.0.2

### Reproduction link
[https://nativescript-vue.org/en/docs/getting-started/quick-start/](https://nativescript-vue.org/en/docs/getting-started/quick-start/)
### Platform and OS info
android

### Steps to reproduce
New raw installation (https://nativescript-vue.org/en/docs/getting-started/quick-start/) with vuex, changing the code it works for a while.
After a few hours it breaks. (deleting `hooks`, `node_modules` & `platforms` doesn't work)
I have to recreate a new installation, copy my modifications from my old project, then it runs fine for the nex few hours.
Now my 3rd project is broken for the same error.

### What is expected?
Running application

### What is actually happening?
```
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
System.err:
System.err: Error calling module function
System.err:
System.err: Error calling module function
System.err:
System.err: Error: java.lang.ClassNotFoundException: com.tns.NativeScriptActivity
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1036)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:604)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:553)
System.err:     com.tns.Runtime.run(Runtime.java:545)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6023)
System.err:     android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
System.err:     android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6798)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/lib/arm, /data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
System.err:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1036)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:604)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:553)
System.err:     com.tns.Runtime.run(Runtime.java:545)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6023)
System.err:     android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
System.err:     android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6798)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: File: "/data/data/org.nativescript.application/files/internal/ts_helpers.js, line: 128, column: 25
System.err:
System.err: StackTrace:
System.err:     Frame: function:'', file:'/data/data/org.nativescript.application/files/internal/ts_helpers.js', line: 128, column: 26
System.err:     Frame: function:'__decorate', file:'/data/data/org.nativescript.application/files/internal/ts_helpers.js', line: 22, column: 19
System.err:     Frame: function:'', file:'', line: 69, column: 26
System.err:     Frame: function:'', file:'', line: 71, column: 2
System.err:     Frame: function:'', file:'', line: 72, column: 30
System.err:     Frame: function:'../node_modules/tns-core-modules/ui/frame/activity.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 1176, column: 1
System.err:     Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
System.err:     Frame: function:'', file:'', line: 12, column: 1
System.err:     Frame: function:'', file:'', line: 41, column: 30
System.err:     Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 250, column: 1
System.err:     Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
System.err:     Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: Error: java.lang.ClassNotFoundException: com.tns.NativeScriptActivity
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1036)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:604)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:553)
System.err:     com.tns.Runtime.run(Runtime.java:545)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6023)
System.err:     android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
System.err:     android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6798)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/lib/arm, /data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
System.err:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1036)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:604)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:553)
System.err:     com.tns.Runtime.run(Runtime.java:545)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6023)
System.err:     android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
System.err:     android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6798)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'', file:'/data/data/org.nativescript.application/files/internal/ts_helpers.js', line: 128, column: 26
System.err:     Frame: function:'__decorate', file:'/data/data/org.nativescript.application/files/internal/ts_helpers.js', line: 22, column: 19
System.err:     Frame: function:'', file:'', line: 69, column: 26
System.err:     Frame: function:'', file:'', line: 71, column: 2
System.err:     Frame: function:'', file:'', line: 72, column: 30
System.err:     Frame: function:'../node_modules/tns-core-modules/ui/frame/activity.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 1176, column: 1
System.err:     Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
System.err:     Frame: function:'', file:'', line: 12, column: 1
System.err:     Frame: function:'', file:'', line: 41, column: 30
System.err:     Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 250, column: 1
System.err:     Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
System.err:     Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: Error: java.lang.ClassNotFoundException: com.tns.NativeScriptActivity
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1036)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:604)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:553)
System.err:     com.tns.Runtime.run(Runtime.java:545)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6023)
System.err:     android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
System.err:     android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6798)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/lib/arm, /data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
System.err:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1036)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:604)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:553)
System.err:     com.tns.Runtime.run(Runtime.java:545)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6023)
System.err:     android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
System.err:     android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6798)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'', file:'/data/data/org.nativescript.application/files/internal/ts_helpers.js', line: 128, column: 26
System.err:     Frame: function:'__decorate', file:'/data/data/org.nativescript.application/files/internal/ts_helpers.js', line: 22, column: 19
System.err:     Frame: function:'', file:'', line: 69, column: 26
System.err:     Frame: function:'', file:'', line: 71, column: 2
System.err:     Frame: function:'', file:'', line: 72, column: 30
System.err:     Frame: function:'../node_modules/tns-core-modules/ui/frame/activity.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 1176, column: 1
System.err:     Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
System.err:     Frame: function:'', file:'', line: 12, column: 1
System.err:     Frame: function:'', file:'', line: 41, column: 30
System.err:     Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 250, column: 1
System.err:     Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
System.err:     Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6026)
System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6798)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: Caused by: com.tns.NativeScriptException:
System.err:
System.err: Error calling module function
System.err:
System.err: Error calling module function
System.err:
System.err: Error: java.lang.ClassNotFoundException: com.tns.NativeScriptActivity
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1036)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:604)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:553)
System.err:     com.tns.Runtime.run(Runtime.java:545)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6023)
System.err:     android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
System.err:     android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6798)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/lib/arm, /data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
System.err:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1036)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:604)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:553)
System.err:     com.tns.Runtime.run(Runtime.java:545)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6023)
System.err:     android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
System.err:     android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6798)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: File: "/data/data/org.nativescript.application/files/internal/ts_helpers.js, line: 128, column: 25
System.err:
System.err: StackTrace:
System.err:     Frame: function:'', file:'/data/data/org.nativescript.application/files/internal/ts_helpers.js', line: 128, column: 26
System.err:     Frame: function:'__decorate', file:'/data/data/org.nativescript.application/files/internal/ts_helpers.js', line: 22, column: 19
System.err:     Frame: function:'', file:'', line: 69, column: 26
System.err:     Frame: function:'', file:'', line: 71, column: 2
System.err:     Frame: function:'', file:'', line: 72, column: 30
System.err:     Frame: function:'../node_modules/tns-core-modules/ui/frame/activity.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 1176, column: 1
System.err:     Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
System.err:     Frame: function:'', file:'', line: 12, column: 1
System.err:     Frame: function:'', file:'', line: 41, column: 30
System.err:     Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 250, column: 1
System.err:     Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
System.err:     Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: Error: java.lang.ClassNotFoundException: com.tns.NativeScriptActivity
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1036)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:604)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:553)
System.err:     com.tns.Runtime.run(Runtime.java:545)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6023)
System.err:     android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
System.err:     android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6798)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/lib/arm, /data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
System.err:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1036)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:604)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:553)
System.err:     com.tns.Runtime.run(Runtime.java:545)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6023)
System.err:     android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
System.err:     android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6798)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'', file:'/data/data/org.nativescript.application/files/internal/ts_helpers.js', line: 128, column: 26
System.err:     Frame: function:'__decorate', file:'/data/data/org.nativescript.application/files/internal/ts_helpers.js', line: 22, column: 19
System.err:     Frame: function:'', file:'', line: 69, column: 26
System.err:     Frame: function:'', file:'', line: 71, column: 2
System.err:     Frame: function:'', file:'', line: 72, column: 30
System.err:     Frame: function:'../node_modules/tns-core-modules/ui/frame/activity.js', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 1176, column: 1
System.err:     Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
System.err:     Frame: function:'', file:'', line: 12, column: 1
System.err:     Frame: function:'', file:'', line: 41, column: 30
System.err:     Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 250, column: 1
System.err:     Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
System.err:     Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: Error: java.lang.ClassNotFoundException: com.tns.NativeScriptActivity
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1036)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:604)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:553)
System.err:     com.tns.Runtime.run(Runtime.java:545)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6023)
System.err:     android.app.ActivityThread.-wrap1(Unknown Source:0)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
System.err:     android.os.Handler.dispatchMessage(Handler.java:105)
System.err:     android.os.Looper.loop(Looper.java:164)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6798)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tns.NativeScriptActivity" on path: DexPathList[[zip file "/data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/base.apk"],nativeLibraryDirectories=[/data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/lib/arm, /data/app/org.nativescript.application-SVv7xr-26Haj-Qi24E9xig==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
System.err:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:379)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:453)
System.err:     java.lang.Class.forName(Class.java:378)
System.err:     com.tns.Runtime.getClassForName(Runtime.java:1036)
System.err:     com.tns.ClassResolver.resolveClass(ClassResolver.java:27)
System.err:     com.tns.Runtime.resolveClass(Runtime.java:604)
```

**Comment by rigor789** [comment]
That seems like an issue with the static binding generator in the NativeScript android build tools. Please provide the version of your NativeScript CLI (`tns --version`) as well as the version specified in `package.json` under the `nativescript/tns-android` section.

**Comment by wendt88** [comment]
NativeScript CLI -> `4.2.4`
tns-android -> `4.2.0`

**Comment by thelonecabbage** [comment]
did anyone solve this?  I'm having the same issue using:

tns --version
6.1.2
"tns-android": {
      "version": "6.1.2"
    },
 "tns-ios": {
      "version": "6.1.0"
 }

It's building on every other machine except for mine!?!?
