### ISSUE TITLE
(Solved) Cannot start newly created vue-cli-template on android emulator

### ISSUE THREAD

**Issue by TunaYagci** [nativescript-vue/nativescript-vue#352]
### Version
2.0.2

### Reproduction link
[https://play.nativescript.org](https://play.nativescript.org)
### Platform and OS info
Android 8 /  NativeScript 4.2.4 / MacOS High Sierra

### Steps to reproduce
Followed these steps:  
https://nativescript-vue.org/en/docs/getting-started/quick-start/
tns run android gives this output:

```js
Successfully synced application org.nativescript.application on device emulator-5554.
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
System.err:
System.err: Cannot compile /data/data/org.nativescript.application/files/app/main.js
System.err:
System.err: SyntaxError: Unexpected identifier
System.err: File: "file:///data/data/org.nativescript.application/files/app/main.js, line: 1, column: 67
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err:
System.err: SyntaxError: Unexpected identifier
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err:
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
System.err: 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
System.err: 	at android.os.Looper.loop(Looper.java:193)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
System.err: Caused by: com.tns.NativeScriptException:
System.err:
System.err: Cannot compile /data/data/org.nativescript.application/files/app/main.js
System.err:
System.err: SyntaxError: Unexpected identifier
System.err: File: "file:///data/data/org.nativescript.application/files/app/main.js, line: 1, column: 67
System.err:
System.err: StackTrace:
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
```

### What is expected?
Run without problem.

### What is actually happening?
Template fails to run.

---
Yeah, it's really frustrating for newcomers like me. I couldn't even build the app.

**Comment by TunaYagci** [comment]
Also happens with Android emulator 7.1.1:  

```
Name: Nexus_5X_API_25

CPU/ABI: Intel Atom (x86)

Target: default [] (API level 25)

Skin: nexus_5x

SD Card: 100M

hw.dPad: no

hw.lcd.height: 1920

runtime.network.speed: full

hw.accelerometer: yes

hw.device.name: Nexus 5X

vm.heapSize: 256

skin.dynamic: yes

hw.device.manufacturer: Google

hw.lcd.width: 1080

hw.gps: yes

hw.initialOrientation: Portrait

image.androidVersion.api: 25

hw.audioInput: yes

image.sysdir.1: system-images/android-25/default/x86/

tag.id: default

showDeviceFrame: yes

hw.camera.back: virtualscene

hw.mainKeys: no

AvdId: Nexus_5X_API_25

hw.camera.front: emulated

hw.lcd.density: 420

avd.ini.displayname: Nexus 5X API 25

hw.arc: false

hw.gpu.mode: auto

hw.device.hash2: MD5:bc5032b2a871da511332401af3ac6bb0

hw.ramSize: 2048

hw.trackBall: no

PlayStore.enabled: false

fastboot.forceColdBoot: no

hw.battery: yes

hw.cpu.ncore: 2

hw.sdCard: yes

tag.display: 

runtime.network.latency: none

hw.keyboard: yes

hw.sensors.proximity: yes

disk.dataPartition.size: 800M

hw.sensors.orientation: yes

avd.ini.encoding: UTF-8

hw.gpu.enabled: yes
```

**Comment by rigor789** [comment]
`--bundle` runs a webpack build, which is required to transpile .vue files. Without `--bundle` you are trying to run .vue files on the device, which fails as it's not a standard file like .js
