### ISSUE TITLE
Nativescript,Vue and Jest Error 

### ISSUE THREAD

**Issue by Arattian** [nativescript-vue/nativescript-vue#357]
### Version
2.0.2

### Reproduction link
[https://github.com/Arattian/Nativescript-vue-jest-issue](https://github.com/Arattian/Nativescript-vue-jest-issue)
### Platform and OS info
Android 9 / Ubuntu 18.04

### Steps to reproduce
npm install
tns run android --bundle
npm test

### What is expected?
Jest test working.

### What is actually happening?
I'm getting the error:

Cannot find module 'tns-core-modules/pl/layouts/layout-base' from 'index.js'

Whenever I'm trying to test something that invokes nativescript-vue like import Vue from 'nativescript-vue'.

---
This application has minimal setup. I need to get Nativescript-vue, typescript, jest, pug and stylus in one project.
Can you add jest support for nativescript-vue like you did for Jasmine, Mocha and Qunit. And is it even possible to add jest in current version of nativescript-vue? Vue CLI provides super easy way to get that all together, i wish to see that feature soon.

**Comment by msaelices** [comment]
@Arattian the repo you linked is not available anymore. Could you provide a repo for testing the issue?

**Comment by evedes** [comment]
Hello everyone! I've passed that error mocking the layout-base module:
`
jest.mock('tns-core-modules/ui/layouts/layout-base', () => {
  return { LayoutBase () { } }
}, { virtual: true })
`
Now I have the following error: 
```    TypeError: Could not load view for: document. ReferenceError: __extends is not defined

    > 1 | import Vue from 'nativescript-vue'
        | ^
      2 | import Vuex from 'vuex'
      3 | import { graphcms } from '~/plugins/apollo'
      4 | import { state, actions, mutations } from 'core-frontend-web/store'

      at getViewClass (node_modules/nativescript-vue/dist/index.js:7396:11)
      at new ElementNode (node_modules/nativescript-vue/dist/index.js:8426:21)
      at new DocumentNode (node_modules/nativescript-vue/dist/index.js:8506:28)
      at Object.<anonymous> (node_modules/nativescript-vue/dist/index.js:13328:43)
      at Object.<anonymous> (app/plugins/vuex.js:1:1)
      at app/components/LandingPage.vue:1859:50
      at Object.<anonymous> (app/components/LandingPage.vue:2262:3)
      at Object.<anonymous> (app/components/LandingPage.spec.js:1:1)
```

Anyone surpassed this problem? Needing some slipstream. ❤️
