### ISSUE TITLE
iOS Embedded

### ISSUE THREAD

**Issue by wilsonpinto** [nativescript-vue/nativescript-vue#362]
Hello, hope someone can help me.

I am trying to embed into my IOS (Objective-C) app using Vuejs with Webpack(vue-cli), I just follow all steps but seems I am strangling to boot my app on the runtime.

### Version
2.0.2

### Reproduction link
[https://github.com/NativeScript/sample-ios-embedded](https://github.com/NativeScript/sample-ios-embedded)
### Platform and OS info
Nativescript 5.0.0rc, vue-cli 3.0.5

### Steps to reproduce
1. tns build ios --bundle

2. follow the steps here https://github.com/NativeScript/sample-ios-embedded

3. build the xcode project

4. app crashes when you click on the action to open the runtime

### What is expected?
Open new view with the nativescript-vue app

### What is actually happening?
App crashes and I get this error:
```Error:` Error: Could not find module 'application'. Computed path '/var/containers/Bundle/Application/6929CE02-AFE6-45C0-8C3E-F6953D6039E2/Vg Native.app/app/tns_modules/application'```

---
Someone that already make it work for nativescript-vue?

PR on the sample-ios-embedded: https://github.com/NativeScript/sample-ios-embedded/issues/12

**Comment by efegure** [comment]
Almost 2 years on this issue, any progress ? We are trying the same thing, we are using webpack as well and we couldn't launch the app inside an empty  (Objective-C) app, js code actually runs but cannot bootstrap with the ios app.
`020-04-28 14:59:44.349190+0300 test3[35431:16674009] ***** Fatal JavaScript exception - application has been terminated. *****
2020-04-28 14:59:44.349366+0300 test3[35431:16674009] Native stack trace:
2020-04-28 14:59:44.349673+0300 test3[35431:16674009] 1   0x10193c80e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
1   0x10193c80e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2020-04-28 14:59:44.349815+0300 test3[35431:16674009] 2   0x10198e784 -[TNSRuntime executeModule:referredBy:]
2   0x10198e784 -[TNSRuntime executeModule:referredBy:]
2020-04-28 14:59:44.350143+0300 test3[35431:16674009] 3   0x100340c96 -[MasterViewController insertNewObject:]
3   0x100340c96 -[MasterViewController insertNewObject:]
2020-04-28 14:59:44.351612+0300 test3[35431:16674009] 4   0x7fff48bc9235 -[UIApplication sendAction:to:from:forEvent:]
4   0x7fff48bc9235 -[UIApplication sendAction:to:from:forEvent:]
2020-04-28 14:59:44.352067+0300 test3[35431:16674009] 5   0x7fff481c470e __45-[_UIButtonBarTargetAction _invoke:forEvent:]_block_invoke
5   0x7fff481c470e __45-[_UIButtonBarTargetAction _invoke:forEvent:]_block_invoke
2020-04-28 14:59:44.352412+0300 test3[35431:16674009] 6   0x7fff481c457c -[_UIButtonBarTargetAction _invoke:forEvent:]
6   0x7fff481c457c -[_UIButtonBarTargetAction _invoke:forEvent:]
2020-04-28 14:59:44.352766+0300 test3[35431:16674009] 7   0x7fff48bc9235 -[UIApplication sendAction:to:from:forEvent:]
7   0x7fff48bc9235 -[UIApplication sendAction:to:from:forEvent:]
2020-04-28 14:59:44.353152+0300 test3[35431:16674009] 8   0x7fff4857a9d3 -[UIControl sendAction:to:forEvent:]
8   0x7fff4857a9d3 -[UIControl sendAction:to:forEvent:]
2020-04-28 14:59:44.353507+0300 test3[35431:16674009] 9   0x7fff4857ad1b -[UIControl _sendActionsForEvents:withEvent:]
9   0x7fff4857ad1b -[UIControl _sendActionsForEvents:withEvent:]
2020-04-28 14:59:44.353859+0300 test3[35431:16674009] 10  0x7fff48579c8c -[UIControl touchesEnded:withEvent:]
10  0x7fff48579c8c -[UIControl touchesEnded:withEvent:]
2020-04-28 14:59:44.354234+0300 test3[35431:16674009] 11  0x7fff48c04a70 -[UIWindow _sendTouchesForEvent:]
11  0x7fff48c04a70 -[UIWindow _sendTouchesForEvent:]
2020-04-28 14:59:44.354604+0300 test3[35431:16674009] 12  0x7fff48c067f5 -[UIWindow sendEvent:]
12  0x7fff48c067f5 -[UIWindow sendEvent:]
2020-04-28 14:59:44.354973+0300 test3[35431:16674009] 13  0x7fff48be0c39 -[UIApplication sendEvent:]
13  0x7fff48be0c39 -[UIApplication sendEvent:]
2020-04-28 14:59:44.355338+0300 test3[35431:16674009] 14  0x7fff48c6b096 __dispatchPreprocessedEventFromEventQueue
14  0x7fff48c6b096 __dispatchPreprocessedEventFromEventQueue
2020-04-28 14:59:44.355697+0300 test3[35431:16674009] 15  0x7fff48c6e262 __handleEventQueueInternal
15  0x7fff48c6e262 __handleEventQueueInternal
2020-04-28 14:59:44.356052+0300 test3[35431:16674009] 16  0x7fff48c64dcb __handleHIDEventFetcherDrain
16  0x7fff48c64dcb __handleHIDEventFetcherDrain
2020-04-28 14:59:44.356272+0300 test3[35431:16674009] 17  0x7fff23d9deb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
17  0x7fff23d9deb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
2020-04-28 14:59:44.356393+0300 test3[35431:16674009] 18  0x7fff23d9dddc __CFRunLoopDoSource0
18  0x7fff23d9dddc __CFRunLoopDoSource0
2020-04-28 14:59:44.356518+0300 test3[35431:16674009] 19  0x7fff23d9d5b4 __CFRunLoopDoSources0
19  0x7fff23d9d5b4 __CFRunLoopDoSources0
2020-04-28 14:59:44.356625+0300 test3[35431:16674009] 20  0x7fff23d981ae __CFRunLoopRun
20  0x7fff23d981ae __CFRunLoopRun
2020-04-28 14:59:44.356747+0300 test3[35431:16674009] 21  0x7fff23d97ac4 CFRunLoopRunSpecific
21  0x7fff23d97ac4 CFRunLoopRunSpecific
2020-04-28 14:59:44.356850+0300 test3[35431:16674009] 22  0x7fff38b2fc1a GSEventRunModal
22  0x7fff38b2fc1a GSEventRunModal
2020-04-28 14:59:44.357203+0300 test3[35431:16674009] 23  0x7fff48bc7f80 UIApplicationMain
23  0x7fff48bc7f80 UIApplicationMain
2020-04-28 14:59:44.357305+0300 test3[35431:16674009] 24  0x100340712 main
24  0x100340712 main
2020-04-28 14:59:44.357417+0300 test3[35431:16674009] 25  0x7fff519521fd start
25  0x7fff519521fd start
2020-04-28 14:59:44.357517+0300 test3[35431:16674009] 26  0x1
26  0x1
2020-04-28 14:59:44.357594+0300 test3[35431:16674009] JavaScript stack trace:
2020-04-28 14:59:44.357694+0300 test3[35431:16674009] createRootView(file:///app/vendor.js:705:93)
at run(file:///app/vendor.js:739:34)
at file:///app/vendor.js:128066:18
at file:///app/vendor.js:115646:25
at file:///app/bundle.js:23436:10
at ./main.native.js(file:///app/bundle.js:23440:34)
at __webpack_require__(file:///app/runtime.js:75:34)
at file:///app/bundle.js:33518:37
at __webpack_require__(file:///app/runtime.js:75:34)
at checkDeferredModules(file:///app/runtime.js:44:42)
at webpackJsonpCallback(file:///app/runtime.js:31:39)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at [native code]
at asyncFunctionResume([native code])
at [native code]
at promiseReactionJob([native code])
2020-04-28 14:59:44.357764+0300 test3[35431:16674009] JavaScript error:
2020-04-28 14:59:44.357884+0300 test3[35431:16674009] file:///app/vendor.js:705:93: JS ERROR Error: Main entry is missing. App cannot be started. Verify app bootstrap.
`

**Comment by wilsonpinto** [comment]
@efegure sorry I just end up to give up and continue the development with native code.

**Comment by rigor789** [comment]
@efegure I have no experience with embedding ns inside a native app - that's why it has been open for a while. 

Looking at your logs though, I have a suspicion of what may be wrong. `nativescript-vue` uses the `launchEvent` to set the root view: 
https://github.com/nativescript-vue/nativescript-vue/blob/3b0debf4c958bff0cb848a7ee0d821f7e1c2c022/platform/nativescript/runtime/index.js#L66-L77

And it may need to be refactored to use `application.run(...)` instead. 

Could you share a repo with me, where I could try a few things?

**Comment by rigor789** [comment]
Update: I got a bit further with this, the bundle is started with a little modification, however it crashes right after right on this line:

https://github.com/NativeScript/NativeScript/blob/c135d2d61e04bdb9da63bb21f4ac73e4721afd22/nativescript-core/application/application.ios.ts#L390

The delegate is found, but `presentNativeScriptApp` is not recognized. 

I suspect it has to do with missing metadata for the delegate.

**Comment by rigor789** [comment]
Update 2: I went real (real real) deep down the rabbit hole, and managed to get it running.

The issues that came up and how I solved them:

**1. `application.run` without parameters does not work when embedding**

NativeScript-Vue calls `application.run` without arguments, and the root view is assigned in the `launchEvent`. This does not work when embedding the application. I manually patched this to work around it: 
https://github.com/nativescript-vue/nativescript-vue/blob/3b0debf4c958bff0cb848a7ee0d821f7e1c2c022/platform/nativescript/runtime/index.js#L66-L76

Changed to (removed the ` on(launchEvent, args => {` listener)

```js
run({
  create() {
    if (self.$el) {
      self.$destroy()
      self = new AppConstructor()
    }

    self.$mount()
    args.root = self.$el.nativeView
  }
})
```

This got me to a different error.

**2. `JS ERROR TypeError: embedderDelegate.presentNativeScriptApp is not a function.`**

This is called from `application.ios.ts`:
https://github.com/NativeScript/NativeScript/blob/c135d2d61e04bdb9da63bb21f4ac73e4721afd22/nativescript-core/application/application.ios.ts#L390

For some reason, the `presentNativeScriptApp` method defined in the [`NativeScriptEmbedder`](https://github.com/NativeScript/NativeScript/blob/f2fb0976c1ea4a9ba5daef7ea7519c9e32f6d122/nativescript-core/platforms/ios/src/NativeScriptEmbedder.h#L12-L14) is not recognized as a function. Even though it is definitely defined on the delegate here:
https://github.com/NativeScript/sample-ios-embedded/blob/7fc819808eabf44318b2af48027dfdfb6d24fa43/CoolApp/CoolApp/ViewController.m#L175-L178

I debugged the generated metadata, and the `NativeScriptEmbedder` looks correct to me: https://gist.github.com/rigor789/9e7298e07cba194bc057dee2a1e1abe2

I patched the call to:
```js
embedderDelegate.presentViewControllerAnimatedCompletion(controller_1, true, null)
```

This got me even further, but ran into a new issue.

**3. `JS ERROR TypeError: undefined is not an object (evaluating 'this._window.rootViewController')`**

The error is thrown in the `rootController` getter here:
https://github.com/NativeScript/NativeScript/blob/c135d2d61e04bdb9da63bb21f4ac73e4721afd22/nativescript-core/application/application.ios.ts#L123-L125

Tracked it down to `this._window` being `undefined` when this is called.

This lead to more debugging, and the issue has been introduced in this commit to NativeScript: https://github.com/NativeScript/NativeScript/commit/5c9a217bc5421aef1bcfc7475936b0ca5e9d1805#diff-116096ff3eda0c66b09b394434499e0cR304-R320

Specifically the call to `setRootViewsSystemAppearanceCssClass`
https://github.com/NativeScript/NativeScript/blob/f2fb0976c1ea4a9ba5daef7ea7519c9e32f6d122/nativescript-core/application/application.ios.ts#L488-L494

calls the `iosApp.systemAppearance` getter: https://github.com/NativeScript/NativeScript/blob/f2fb0976c1ea4a9ba5daef7ea7519c9e32f6d122/nativescript-core/application/application.ios.ts#L127-L139

Which calls `this.rootController.traitCollection.userInterfaceStyle;`

Specifically `this.rootController` is a getter that crashes the app.

So the conclusion of this rabbit hole is that this block of code causes the crash:
https://github.com/NativeScript/NativeScript/blob/f2fb0976c1ea4a9ba5daef7ea7519c9e32f6d122/nativescript-core/application/application.ios.ts#L396-L414

`this._window` is set by the `iosApp.notifyAppStarted();` call, which is at the very end. 

I moved the call above the `setRootViewsSystemAppearanceCssClass` block, and the app no longer crashes, and it shows the `nativescript-vue` app correctly.

**Comment by rigor789** [comment]
How we can fix these:

1. this can be fixed in `nativescript-vue` by a simple refactor
2. this should be debugged further to see why `presentNativeScriptApp` is not found on the delegate, even though it is there.
3. this can be fixed in the [NativeScript](https://github.com/NativeScript/NativeScript) repo by either changing the order of the calls to call `iosApp.notifyAppStarted();` first - or setting the window earlier in the call stack.

**Comment by wilsonpinto** [comment]
> How we can fix these:
> 
> 1. this can be fixed in `nativescript-vue` by a simple refactor
> 2. this should be debugged further to see why `presentNativeScriptApp` is not found on the delegate, even though it is there.
> 3. this can be fixed in the [NativeScript](https://github.com/NativeScript/NativeScript) repo by either changing the order of the calls to call `iosApp.notifyAppStarted();` first - or setting the window earlier in the call stack.

nice @rigor789 I will also give a try later again, this it's for sure a factor to use this framework

**Comment by efegure** [comment]
@rigor789  wow i wasn't actually waiting for a response, thank you for the detailed explanation about this, the first option can be the easiest for you guys to fix i think. Probably this is not a priority for the ns-vue team but it would be great to do this if this an easy refactor like you mentioned. 
Thanks again and best wishes :)

**Comment by rigor789** [comment]
@efegure all 3 need to be fixed for this to be a smooth experience. I have it on my radar to fix all 3, but I can't promise anything - it's been pretty busy lately...

1 and 3 are fairly simple to fix - 2 needs more debugging to find the root cause why the function is not recognized despite it being there!

**Comment by efegure** [comment]
@rigor789 hello, any updates on this issue ?
