### ISSUE TITLE
tns preview --bundle not working 

### ISSUE THREAD

**Issue by bcazu** [nativescript-vue/nativescript-vue#379]
### Version
2.0.2

### Reproduction link
[https://github.com/bcazu/-NativeScriptVue](https://github.com/bcazu/-NativeScriptVue)
### Platform and OS info
Android 6.0 / NativeScript 4 / Windows 10

### Steps to reproduce
My project is with {N} 4, I followed the paspos to update it to {N} 5 according to https://nativescript-vue.org/blog/upgrading-to-nativescript-5/ however after finishing the steps and executing tns preview --bundle does not work If I create a new project following the steps of https://nativescript-vue.org/en/docs/getting-started/quick-start/ tns preview --bundle does not work either. And if I create a project with tns create if the command tns preview --bundle works for me.

### What is expected?
-

### What is actually happening?
-

---

The error:

Webpack compilation complete. Watching for file changes.
Webpack build done!
Plugin nativescript-socket.io is not included in preview app on device 10d2f03d-cbb4-4319-95e1-d30dc58f6642 and will not work.
Start syncing changes for platform android.
Copying template files...
Platform android successfully added. v5.0.0
Executing before-shouldPrepare hook from S:\documentos\Android\fontAw\hooks\before-shouldPrepare\nativescript-dev-webpack.js
Preparing project...
Executing before-prepareJSApp hook from S:\documentos\Android\fontAw\hooks\before-prepareJSApp\nativescript-dev-webpack.js
Project successfully prepared (android)
Executing after-prepare hook from S:\documentos\Android\fontAw\hooks\after-prepare\nativescript-dev-webpack.js
Successfully synced changes for platform android.
Error: PubNub call failed, check status for details
    at new PubNubError (C:\Users\sabi\AppData\Roaming\npm\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:8:31)
    at onResponse (C:\Users\sabi\AppData\Roaming\npm\node_modules\nativescript\node_modules\pubnub\lib\core\components\core\components\endpoint.js:126:32)
    at <anonymous> (C:\Users\sabi\AppData\Roaming\npm\node_modules\nativescript\node_modules\pubnub\lib\networking\modules\networking\modules\web-node.js:59:17)
    at Request.callback (C:\Users\sabi\AppData\Roaming\npm\node_modules\nativescript\node_modules\superagent\lib\node\index.js:728:3)
    at RequestBase._timeoutError (C:\Users\sabi\AppData\Roaming\npm\node_modules\nativescript\node_modules\superagent\lib\request-base.js:676:8)
    at Timeout.<anonymous> (C:\Users\sabi\AppData\Roaming\npm\node_modules\nativescript\node_modules\superagent\lib\request-base.js:685:12)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

**Comment by rigor789** [comment]
> Plugin nativescript-socket.io is not included in preview app on device 10d2f03d-cbb4-4319-95e1-d30dc58f6642 and will not work.

You have VueDevtools enabled by any chance? 

As it will not work with preview, since the socket-io plugin is not included in the Preview app.

**Comment by bcazu** [comment]
Yes, I have it installed, socket-io plugin and also. You can install a proyect whint documentation of NativeScript-Vue? 
![image](https://user-images.githubusercontent.com/33225101/48638681-4a466780-e99f-11e8-9506-9f4d6a63ea5a.png)

**Comment by rigor789** [comment]
Well this is expected, the preview app has a limited amount of plugins pre-installed.

tns preview is like the Playground, with the difference that you can work in your own editor.

In your case, either use `tns run android --bundle` (or ios) which will work as long as you have your system ready for native development (xcode for ios, android sdk/build tools etc for android).
