### ISSUE TITLE
How to use default page in multiple frames?

### ISSUE THREAD

**Issue by leokim1129** [nativescript-vue/nativescript-vue#381]
when using defaultPage in frame i am getting error.

Playgound : https://play.nativescript.org/?template=play-vue&id=cgkSHF&v=2

    <Page class="page">
        <ActionBar title="Home" class="action-bar" />

        <TabView androidTabsPosition="bottom">
            <TabViewItem title="Tab 1">
                <Frame defaultPage="components/test1.vue"></Frame>
            </TabViewItem>
            <TabViewItem title="Tab 2">
                <Frame defaultPage="components/test2.vue"></Frame>
            </TabViewItem>
        </TabView>
    </Page>

`TypeError: Cannot read property 'onNavigatingTo' of undefined
File: "file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js, line: 157, column: 37

StackTrace: 
Frame: function:'FrameBase._onNavigatingTo', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 266, column: 37
Frame: function:'FrameBase.performNavigation', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 238, column: 14
Frame: function:'FrameBase._processNextNavigationEntry', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame-common.js', line: 231, column: 22
Frame: function:'Frame._processNextNavigationEntry', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 143, column: 58
Frame: function:'Frame._onAttachedToWindow', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 118, column: 14
Frame: function:'AttachListener.onViewAttachedToWindow', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 35, column: 27
Frame: function:'FragmentPagerAdapter.finishUpdate', file:'file:///data/data/org.nativescript.preview/files/app/tns_modules/tns-core-modules/ui/tab-view/tab-view.js', line: 157, column: 38

at com.tns.Runtime.callJSMethodNative(Native Method)
at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
at com.tns.Runtime.callJSMethod(Runtime.java:983)
at com.tns.Runtime.callJSMethod(Runtime.java:967)
at com.tns.Runtime.callJSMethod(Runtime.java:959)
at com.tns.gen.android.support.v4.view.PagerAdapter_view_69_32_FragmentPagerAdapter.finishUpdate(PagerAdapter_view_69_32_FragmentPagerAdapter.java:92)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
at android.support.v4.view.ViewPager.populate(ViewPager.java:1086)
at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1616)
at android.view.View.measure(View.java:23265)
at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
at android.view.View.measure(View.java:23265)
at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
at org.nativescript.widgets.MeasureHelper.measureChildFixedColumnsAndRows(GridLayout.java:1056)
at org.nativescript.widgets.MeasureHelper.measure(GridLayout.java:866)
at org.nativescript.widgets.GridLayout.onMeasure(GridLayout.java:280)
at android.view.View.measure(View.java:23265)
at org.nativescript.widgets.CommonLayoutParams.measureChild(CommonLayoutParams.java:262)
at org.nativescript.widgets.ContentLayout.onMeasure(ContentLayout.java:32)
at android.view.View.measure(View.java:23265)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
at android.view.View.measure(View.java:23265)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
at android.view.View.measure(View.java:23265)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at android.view.View.measure(View.java:23265)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
at android.view.View.measure(View.java:23265)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:898)
at android.view.View.measure(View.java:23265)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2873)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1910)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2165)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1779)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7810)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
at android.view.Choreographer.doCallbacks(Choreographer.java:723)
at android.view.Choreographer.doFrame(Choreographer.java:658)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6938)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)`

**Comment by PieterHartzer** [comment]
@leokim1129 If you managed to solve the issue, please post a solution or link to a solution here.  I am struggling with the same issue and no doubt others will too.

**Comment by rigor789** [comment]
My answer from slack:

> Add it in the default slot as `<Frame><YourDefaultPageComponent/></Frame>`

**Comment by PieterHartzer** [comment]
I [submitted a change](https://github.com/nativescript-vue/nativescript-vue.org/pull/239) to the documentation on the website so that this is on there too.
