### ISSUE TITLE
Wanted to publish for Play Store but it crashes with final build

### ISSUE THREAD

**Issue by Mxkkxa** [nativescript-vue/nativescript-vue#386]
This is how I try to build:
```
tns build android --release --key-store-path ./top-secret.jks --key-store-password <mypw> --key-store-alias MoonNews --key-store-alias-password <mypw>
```

It builds without error, and it also runs with tns run android --hmr or tns run android --bundle.

It is the final .apk that crashes.
```
FATAL EXCEPTION: main
Process: org.moonnews.application, PID: 12701
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Cannot compile /data/data/org.moonnews.application/files/app/main.js
SyntaxError: Unexpected identifier
File: "file:///data/data/org.moonnews.application/files/app/main.js, line: 1, column: 67
StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
SyntaxError: Unexpected identifier
File: "<unknown>, line: 1, column: 265
StackTrace: 
	Frame: function:'require', file:'', line: 1, column: 266
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5678)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
Caused by: com.tns.NativeScriptException: 
Cannot compile /data/data/org.moonnews.application/files/app/main.js
SyntaxError: Unexpected identifier
File: "file:///data/data/org.moonnews.application/files/app/main.js, line: 1, column: 67
```

**Comment by rigor789** [comment]
Missing `--bundle` flag from the build command.

**Comment by Mxkkxa** [comment]
@rigor789 Thanks, solved ^^'
