### ISSUE TITLE
2.3.0-rc.0 - hmr error with change inside style tags

### ISSUE THREAD

**Issue by jawa-the-hutt** [nativescript-vue/nativescript-vue#503]
### Version
2.3.0-rc.0

### Reproduction link
[https://github.com/jawa-the-hutt/nativescript-vue-hmr-issue](https://github.com/jawa-the-hutt/nativescript-vue-hmr-issue)
### Platform and OS info
Android API 28 & IOS 12.2 / Nativescript 5.4.0 / MacOS

### Steps to reproduce
Run the project with hmr:
`npm run serve:android -- --hmr`
or
`npm run serve:ios -- --hmr`

Make a change to the CSS inside the App.vue `<style>` tags.  Just comment or uncomment out something, save and the error will be triggered.

### What is expected?
HMR reloads updates to the styling without any issues.

### What is actually happening?
HMR says it's successfully updating, but then an error is thrown in Android and IOS.

IOS error: 
```
Webpack compilation complete. Watching for file changes.
Webpack build done!
Successfully transferred bundle.c7ee40a07b452b13139d.hot-update.js on device 84AFB929-B80D-46A3-872D-306D39472C77.
Successfully transferred c7ee40a07b452b13139d.hot-update.json on device 84AFB929-B80D-46A3-872D-306D39472C77.
No type errors found
Version: typescript 3.5.1
Time: 1452ms
NativeScript debugger has opened inspector socket on port 18183 for org.nativescript.application.
Refreshing application on device 84AFB929-B80D-46A3-872D-306D39472C77...
CONSOLE WARN Loading inspector modules failed:  Error: Could not find module 'inspector_modules.js'. Computed path '/Users/garygambill/Library/Developer/CoreSimulator/Devices/84AFB929-B80D-46A3-872D-306D39472C77/data/Containers/Bundle/Application/347B2E07-1A66-46EF-8BD9-0D2920779425/test9.app/app/tns_modules/inspector_modules.js'.
NativeScript debugger attached.
CONSOLE INFO file:///app/vendor.js:115:32: HMR: Checking for updates to the bundle with hmr hash c7ee40a07b452b13139d.
CONSOLE INFO file:///app/vendor.js:115:32: HMR: The following modules were updated:
CONSOLE INFO file:///app/vendor.js:115:32: HMR:          ↻ ../node_modules/nativescript-dev-webpack/style-hot-loader.js!../node_modules/nativescript-dev-webpack/apply-css-loader.js!../node_modules/css-loader/index.js?!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/postcss-loader/src/index.js?!../node_modules/sass-loader/lib/loader.js?!../node_modules/vue-loader/lib/index.js?!../node_modules/string-replace-loader/index.js?!./App.vue?vue&type=style&index=0&id=472cff63&scoped=true&native=true&lang=scss&
CONSOLE INFO file:///app/vendor.js:115:32: HMR: Successfully applied update with hmr hash c7ee40a07b452b13139d. App is up to date.
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x10a356cdf NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10a38cee0 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x10acb1956 ffi_closure_unix64_inner
4   0x10acb237a ffi_closure_unix64
5   0x10d6883e4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__
6   0x10d687ff2 __CFRunLoopDoTimer
7   0x10d68785a __CFRunLoopDoTimers
8   0x10d681efc __CFRunLoopRun
9   0x10d681302 CFRunLoopRunSpecific
10  0x1146102fe GSEventRunModal
11  0x10ea6cba2 UIApplicationMain
12  0x10acb21bd ffi_call_unix64
13  0x1213a8e20
JavaScript stack trace:
1   _onLivesync@file:///app/vendor.js:15177:97
2   __onLiveSyncCore@file:///app/vendor.js:15220:21
3   livesync@file:///app/vendor.js:14824:17
4   __onLiveSync@file:///app/vendor.js:15361:32
5   @file:///app/bundle.js:638:35
6   invoke@file:///app/vendor.js:26407:26
7   tick@file:///app/vendor.js:26355:20
8   UIApplicationMain@[native code]
9   _start@file:///app/vendor.js:15267:22
10  run@file:///app/vendor.js:15309:9
11  $start@file:///app/vendor.js:14598:18
12  @file:///app/bundle.js:669:10
13  ./main.native.ts@file:///app/bundle.js:671:34
14  __webpack_require__@file:///app/runtime.js:751:34
15  fn@file:///app/runtime.js:121:39
16  @file:///app/bundle.js:918:37
17  __webpack_require__@file:///app/runtime.js:751:34
18  checkDeferredModules@file:///app/runtime.js:44:42
19  webpackJsonpCallback@file:///app/runtime.js:31:39
20  anonymous@file:///app/bundle.js:2:61
21  evaluate@[native code]
22  moduleEvaluation@[native code]
23  promiseReactionJob@[native code]
24  require@[native code]
25  anonymous<…>
JavaScript error:
file:///app/vendor.js:15177:97: JS ERROR TypeError: undefined is not an object (evaluating 'getMainEntry().moduleName')
Successfully synced application org.nativescript.application on device 84AFB929-B80D-46A3-872D-306D39472C77.
```

Android Error:

```
Webpack compilation complete. Watching for file changes.
Webpack build done!
Successfully transferred bundle.74461061ba2ed907e743.hot-update.js on device emulator-5554.
Successfully transferred 74461061ba2ed907e743.hot-update.json on device emulator-5554.
JS: HMR: Checking for updates to the bundle with hmr hash 74461061ba2ed907e743.
Refreshing application on device emulator-5554...
JS: HMR: The following modules were updated:
JS: HMR:          ↻ ../node_modules/nativescript-dev-webpack/style-hot-loader.js!../node_modules/nativescript-dev-webpack/apply-css-loader.js!../node_modules/css-loader/index.js?!../node_modules/vue-loader/lib/loaders/stylePostLoader.js!../node_modules/postcss-loader/src/index.js?!../node_modules/sass-loader/lib/loader.js?!../node_modules/vue-loader/lib/index.js?!../node_modules/string-replace-loader/index.js?!./App.vue?vue&type=style&index=0&id=472cff63&scoped=true&native=true&lang=scss&
JS: HMR: Successfully applied update with hmr hash 74461061ba2ed907e743. App is up to date.
System.err: com.tns.NativeScriptException: 
System.err: Calling js method run failed
System.err: 
System.err: TypeError: Cannot read property 'moduleName' of undefined
System.err: File: "file:///data/data/org.nativescript.application/files/app/vendor.js, line: 40086, column: 108
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'reloadPage', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 40086, column: 109
System.err:     Frame: function:'livesync', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 14824, column: 5
System.err:     Frame: function:'__onLiveSync', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 15139, column: 24
System.err:     Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 643, column: 20
System.err:     Frame: function:'invoke', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 26650, column: 21
System.err:     Frame: function:'run', file:'file:///data/data/org.nativescript.application/files/app/vendor.js', line: 26656, column: 7
System.err: 
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1203)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1083)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1070)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1050)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1042)
System.err:     at com.tns.gen.java.lang.Runnable.run(Runnable.java:17)
System.err:     at android.os.Handler.handleCallback(Handler.java:873)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:193)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6669)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Successfully synced application org.nativescript.application on device emulator-5554.
No type errors found
Version: typescript 3.5.1
Time: 1614ms
```

---
The test repo in question is using the `vue-cli-plugin-nativescript-vue` plugin so I'm not sure if this issue occurs with a project not using the CLI plugin or not.

**Comment by jawa-the-hutt** [comment]
I do want to confirm that the issue did not occur with the test repo with NS-Vue 2.2.0.  It was only after upgrading to 2.3.0-rc.0 that the HMR issue started to occur.

**Comment by trungking** [comment]
HMR work for me only in **2.2.0** 
**2.2.1**, **2.2.2** or **2.3.0-rc** not work with both **style** and **template** tag
