### ISSUE TITLE
App using custom component with props crashes when `$navigateTo` with `{ clearHistory: true }`

### ISSUE THREAD

**Issue by kulikala** [nativescript-vue/nativescript-vue#551]
### Version
2.4.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=S16cEZ&v=3](https://play.nativescript.org/?template=play-vue&id=S16cEZ&v=3)
### Platform and OS info
iOS 12.4.1 / NativeScript 6.1.0 / macOS 10.14.6

### Steps to reproduce
1. Preview the app
2. Tap "Go to Secondary page without history"
3. App crashes

### What is expected?
The app should keep running without crashing.

### What is actually happening?
The app crashed.

Stack trace:
```
[kulikala]: '{NSVue (Vue: 2.6.10 | NSVue: 2.4.0)} -> CreateElement(NativePage)'
[kulikala]: '{NSVue (Vue: 2.6.10 | NSVue: 2.4.0)} -> CreateElement(NativeActionBar)'
[kulikala]: '{NSVue (Vue: 2.6.10 | NSVue: 2.4.0)} -> AppendChild(ElementNode(nativepage), ElementNode(nativeactionbar))'
[kulikala]: '{NSVue (Vue: 2.6.10 | NSVue: 2.4.0)} -> CreateElement(nativestacklayout)'
[kulikala]: '{NSVue (Vue: 2.6.10 | NSVue: 2.4.0)} -> CreateElement(nativelabel)'
[kulikala]: '{NSVue (Vue: 2.6.10 | NSVue: 2.4.0)} -> CreateElement(nativescrollview)'
[kulikala]: '{NSVue (Vue: 2.6.10 | NSVue: 2.4.0)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativelabel))'
[kulikala]: '{NSVue (Vue: 2.6.10 | NSVue: 2.4.0)} -> AppendChild(ElementNode(nativepage), ElementNode(nativescrollview))'
[kulikala]: '{NSVue (Vue: 2.6.10 | NSVue: 2.4.0)} -> AppendChild(ElementNode(nativescrollview), ElementNode(nativestacklayout))'
[kulikala]: The Preview app has terminated unexpectedly. Please run it again to get a detailed crash report.
[kulikala]: 2019-09-12 02:19:51.976 nsplaydev[2124:485791] PlayLiveSync: Successfully sent log message SyG1jjILH
2019-09-12 02:19:51.977 nsplaydev[2124:485791] PlayLiveSync: Successfully sent log message SyG1jjILH
2019-09-12 02:19:51.977 nsplaydev[2124:485791] PlayLiveSync: Successfully sent log message SyG1jjILH
2019-09-12 02:19:51.988 nsplaydev[2124:485791] PlayLiveSync: Successfully sent log message SyG1jjILH
2019-09-12 02:19:51.989 nsplaydev[2124:485791] PlayLiveSync: Successfully sent log message SyG1jjILH
2019-09-12 02:19:51.990 nsplaydev[2124:485791] PlayLiveSync: Successfully sent log message SyG1jjILH
2019-09-12 02:19:51.999 nsplaydev[2124:485791] PlayLiveSync: Successfully sent log message SyG1jjILH
2019-09-12 02:19:52.000 nsplaydev[2124:485791] PlayLiveSync: Successfully sent log message SyG1jjILH
2019-09-12 02:19:52.003 nsplaydev[2124:485791] PlayLiveSync: Successfully sent log message SyG1jjILH
2019-09-12 02:19:52.275 nsplaydev[2124:485791] ***** Fatal JavaScript exception - application has been terminated. *****
2019-09-12 02:19:52.275 nsplaydev[2124:485791] Native stack trace:
1 0x1032e32fc NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2 0x103319a38 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3 0x103e0cafc ffi_closure_SYSV_inner
4 0x103e101b4 .Ldo_closure
5 0x1dfd38a20 <redacted>
6 0x1dfd39384 <redacted>
7 0x1dfc9c244 <redacted>
8 0x1d3c2207c <redacted>
9 0x1dfc91640 <redacted>
10 0x1dfd5bf24 <redacted>
11 0x1dfd6c1f4 <redacted>
12 0x1e0767d1c <redacted>
13 0x1e073ea74 <redacted>
14 0x1e073f048 <redacted>
15 0x1d3c4b5a0 <redacted>
16 0x1e073f0e8 <redacted>
17 0x1d3c4b5a0 <redacted>
18 0x1b7f213c8 <redacted>
19 0x1b34117d4 <redacted>
20 0x1b33bf008 <redacted>
21 0x1b396432c <redacted>
22 0x1b395f264 <redacted>
23 0x1b395e7c0 CFRunLoopRunSpecific
24 0x1b5b5f79c GSEventRunModal
25 0x1e02dcc38 UIApplicationMain
26 0x103e10044 ffi_call_SYSV
27 0x103e0c220 ffi_call_int
28 0x103e0bd1c ffi_call
29 0x1032a4f60 NativeScript::FunctionWrapper::call(JSC::ExecState*)
30 0x103e0af28 llint_entry
31 0x103e092a4 llint_entry
2019-09-12 02:19:52.280 nsplaydev[2124:485791] JavaScript stack trace:
2019-09-12 02:19:52.280 nsplaydev[2124:485791] destroy(file:///app/tns_modules/nativescript-vue/dist/index.js:5552:27)
at invokeDestroyHook(file:///app/tns_modules/nativescript-vue/dist/index.js:6959:59)
at invokeDestroyHook(file:///app/tns_modules/nativescript-vue/dist/index.js:6964:26)
at patch(file:///app/tns_modules/nativescript-vue/dist/index.js:7312:46)
at $destroy(file:///app/tns_modules/nativescript-vue/dist/index.js:6390:17)
at destroy(file:///app/tns_modules/nativescript-vue/dist/index.js:5554:35)
at invokeDestroyHook(file:///app/tns_modules/nativescript-vue/dist/index.js:6959:59)
at patch(file:///app/tns_modules/nativescript-vue/dist/index.js:7312:46)
at $destroy(file:///app/tns_modules/nativescript-vue/dist/index.js:6390:17)
at disposeNativeView(file:///app/tns_modules/nativescript-vue/dist/index.js:8707:30)
at _tearDownUI(file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:564:27)
at _removeViewCore(file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:465:23)
at _removeView(file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:458:25)
at _removeEntry(file:///app/tns_modules/tns-core-modules/ui/frame/frame-common.js:117:24)
at _updateBackstack(file:///app/tns_modules/tns-core-modules/ui/frame/frame-common.js:183:24)
at setCurrent(file:///app/tns_modules/tns-core-modules/ui/frame/frame.js:47:28)
at viewDidAppear(file:///app/tns_modules/tns-core-modules/ui/page/page.js:105:23)
at UIApplicationMain([native code])
at _start(file:///app/tns_modules/tns-core-modules/application/application.js:295:22)
at run(file:///app/tns_modules/tns-core-modules/application/application.js:323:9)
at $start(file:///app/tns_modules/nativescript-vue/dist/index.js:14050:18)
at anonymous(file:///app/app.js:20:10)
at evaluate([native code])
at moduleEvaluation([native code])
at promiseReactionJob([native code])
2019-09-12 02:19:52.281 nsplaydev[2124:485791] JavaScript error:
file:///app/tns_modules/nativescript-vue/dist/index.js:5552:27: JS ERROR TypeError: undefined is not an object (evaluating 'componentInstance._isDestroyed')
2019-09-12 02:19:52.282 nsplaydev[2124:485791] PlayLiveSync: Uncaught Exception
2019-09-12 02:19:52.282 nsplaydev[2124:485791] PlayLiveSync: Sending crash report
2019-09-12 02:19:56.283 nsplaydev[2124:485791] *** JavaScript call stack:
(
0 UIApplicationMain@[native code]
1 _start@file:///app/tns_modules/tns-core-modules/application/application.js:295:22
2 run@file:///app/tns_modules/tns-core-modules/application/application.js:323:9
3 $start@file:///app/tns_modules/nativescript-vue/dist/index.js:14050:18
4 anonymous@file:///app/app.js:20:10
5 evaluate@[native code]
6 moduleEvaluation@:1:11
7 promiseReactionJob@:1:11
)
2019-09-12 02:19:56.285 nsplaydev[2124:485791] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not an object (evaluating 'componentInstance._isDestroyed')
at
destroy(file:///app/tns_modules/nativescript-vue/dist/index.js:5552:27)
at invokeDestroyHook(file:///app/tns_modules/nativescript-vue/dist/index.js:6959:59)
at invokeDestroyHook(file:///app/tns_modules/nativescript-vue/dist/index.js:6964:26)
at patch(file:///app/tns_modules/nativescript-vue/dist/index.js:7312:46)
at $destroy(file:///app/tns_modules/nativescript-vue/dist/index.js:6390:17)
at destroy(file:///app/tns_modules/nativescript-vue/dist/index.js:5554:35)
at invokeDestroyHook(file:///app/tns_modules/nativescript-vue/dist/index.js:6959:59)
at patch(file:///app/tns_modules/nativescript-vue/dist/index.js:7312:46)
at $destroy(file:///app/tns_modules/nativescript-vue/dist/index.js:6390:17)
at disposeNativeView(file:///app/tns_modules/nativescript-vue/dist/index.js:8707:30)
at _tearDownUI(file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:564:27)
at _removeViewCore(file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:465:23)
at _removeView(file:///app/tns_modules/tns-core-modules/ui/core/view-base/view-base.js:458:25)
at _removeEntry(file:///app/tns_modules/tns-core-modules/ui/frame/frame-common.js:117:24)
at _updateBackstack(file:///app/tns_modules/tns-core-modules/ui/frame/frame-common.js:183:24)
at setCurrent(file:///app/tns_modules/tns-core-modules/ui/frame/frame.js:47:28)
at viewDidAppear(file:///app/tns_modules/tns-core-modules/ui/page/page.js:105:23)
at UIApplicationMain([native code])
at _start(file:///app/tns_modules/tns-core-modules/application/application.js:295:22)
at run(file:///app/tns_modules/tns-core-modules/application/application.js:323:9)
at $start(file:///app/tns_modules/nativescript-vue/dist/index.js:14050:18)
at anonymous(file:///app/app.js:20:10)
at evaluate([native code])
at moduleEvaluation([native code])
at promiseReactionJob([native code])
', reason: '(null)'
*** First throw call stack:
(0x1b39d298c 0x1b2bab9f8 0x1032e3778 0x103319a38 0x103e0cafc 0x103e101b4 0x1dfd38a20 0x1dfd39384 0x1dfc9c244 0x1d3c2207c 0x1dfc91640 0x1dfd5bf24 0x1dfd6c1f4 0x1e0767d1c 0x1e073ea74 0x1e073f048 0x1d3c4b5a0 0x1e073f0e8 0x1d3c4b5a0 0x1b7f213c8 0x1b34117d4 0x1b33bf008 0x1b396432c 0x1b395f264 0x1b395e7c0 0x1b5b5f79c 0x1e02dcc38 0x103e10044 0x103e0c220 0x103e0bd1c 0x1032a4f60 0x103e0af28 0x103e092a4 0x103e092a4 0x103e092a4 0x103e092a4 0x103df4d4c 0x103a81914 0x103c569c8 0x1032be2a4 0x103425bf8 0x103e0ac8c 0x103e092a4 0x103e092a4 0x103df4d4c 0x103a81914 0x103c56b94 0x10341f130 0x1032b4548 0x1033281d0 0x1044061f8 0x102acb420 0x1b34228e0)
libc++abi.dylib: terminating with uncaught exception of type NSException
2019-09-12 02:19:56.285 nsplaydev[2124:485791] PlayLiveSync: Uncaught Exception
```

---
The crash does not happen if:

* the custom component does not have props
* the custom component is not registered in the navigated page (that is `Secondary.vue`)
  - it's not required to USE the registered component
* the custom component is not used in the current page (that is `Main.vue`)
* invoke `$navigateTo` without option `{ clearHistory: true }`

**Comment by msaelices** [comment]
@kulikala I could not reproduce the issue. Please see the following screencast:

![issue-551 mov](https://user-images.githubusercontent.com/136875/64950987-09e49e00-d87d-11e9-99fe-75774923678b.gif)

**Comment by kulikala** [comment]
Please run `tns preview` to reproduce.

I've also run `tns run ios` on both the simulator and my device, the crash did not happen.

Though I'm developing my app using `tns preview` so I'll keep investigating for reproductive code.

**Comment by kulikala** [comment]
I don't know why this happens exclusively on Playground...

I found this line in the device logs:
```
[kulikala]: '{NSVue (Vue: 2.6.10 | NSVue: 2.4.0)} -> CreateElement(NativePage)'
[kulikala]: ERROR: [Vue warn]: Error in nextTick: "TypeError: undefined is not an object (evaluating 'vm.$scopedSlots')"
```

It seems this warning occurs in `function updateChildComponent(vm, propsData, listeners, parentVnode, renderChildren)` if the first parameter `vm` is empty.

In `MyComponent.vue`, I found `created()` and `beforeMount()` life cycle hook is called, but `mounted()` is not on Playground.
As a result, `vm._vnode.componentInstance` became empty, which leads to the crash in `componentVNodeHooks.destroy()` function.

**Comment by msaelices** [comment]
@VladimirAmiorkov I guess this problem is probably caused because of a playground integration issue.

**Comment by msaelices** [comment]
I've reproduced the same issue as @kulikala, but only if I execute the code with `tns preview`
