### ISSUE TITLE
App doesn't start after build, only android

### ISSUE THREAD

**Issue by marcoindaweb** [nativescript-vue/nativescript-vue#556]
### Version
2.4.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=TJGi1g&v=9](https://play.nativescript.org/?template=play-vue&id=TJGi1g&v=9)
### Platform and OS info
Android 9.0 / NativeScript Vue 2.4.0 / MacOS 10.14.6

### Steps to reproduce
' tns build android --clean ' in console, and  install .apk in android phone.

### What is expected?
App start in android.

### What is actually happening?
Error:
An uncaught Exception occurred on "main" thread.
Calling js method onCreateView failed
Error: java.lang.NullPointerException
    android.widget.TextView.setTextColor(TextView.java:4309)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
    com.tns.Runtime.callJSMethod(Runtime.java:1083)
    com.tns.Runtime.callJSMethod(Runtime.java:1063)
    com.tns.Runtime.callJSMethod(Runtime.java:1055)
    com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
    android.os.Handler.handleCallback(Handler.java:873)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:6703)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

StackTrace:
	TextBase.<computed>(file:///data/data/org.nativescript.projectname/files/app/vendor.js:74190:38)
	at applyAllNativeSetters(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50385:31)
	at initNativeView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50289:5)
	at ViewBase.onResumeNativeUpdates(file:///data/data/org.nativescript.projectname/files/app/vendor.js:51401:18)
	at ViewBase._resumeNativeUpdates(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50932:12)
	at ViewBase.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50878:10)
	at View.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:53296:31)
	at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50981:20)
	at ViewBase.callFunctionWithSuper(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50970:5)
	at ViewBase.callLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50980:10)
	at ViewBase.loadView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:51157:12)
	at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50881:13)
	at LayoutBaseCommon.eachChildView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:62391:20)
	at ViewCommon.eachChild(file:///data/data/org.nativescript.projectname/files/app/vendor.js:52759:10)
	at ViewBase.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50880:10)
	at View.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:53296:31)
	at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50981:20)
	at ViewBase.callFunctionWithSuper(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50970:5)
	at ViewBase.callLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50980:10)
	at ViewBase.loadView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:51157:12)
	at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50881:13)
	at LayoutBaseCommon.eachChildView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:62391:20)
	at ViewCommon.eachChild(file:///data/data/org.nativescript.projectname/files/app/vendor.js:52759:10)
	at ViewBase.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50880:10)
	at View.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:53296:31)
	at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50981:20)
	at ViewBase.callFunctionWithSuper(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50970:5)
	at ViewBase.callLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50980:10)
	at ViewBase.loadView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:51157:12)
	at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50881:13)
	at LayoutBaseCommon.eachChildView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:62391:20)
	at ViewCommon.eachChild(file:///data/data/org.nativescript.projectname/files/app/vendor.js:52759:10)
	at ViewBase.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50880:10)
	at View.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:53296:31)
	at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50981:20)
	at ViewBase.callFunctionWithSuper(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50970:5)
	at ViewBase.callLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50980:10)
	... 24 more

---
When the app start the splash screen is visible for some seconds, then it crash.
'tns doctor' don't detect any issues.

**Comment by KonstantinObuhov** [comment]
> ### Version
> 2.4.0
> 
> ### Reproduction link
> https://play.nativescript.org/?template=play-vue&id=TJGi1g&v=9
> 
> ### Platform and OS info
> Android 9.0 / NativeScript Vue 2.4.0 / MacOS 10.14.6
> 
> ### Steps to reproduce
> ' tns build android --clean ' in console, and install .apk in android phone.
> 
> ### What is expected?
> App start in android.
> 
> ### What is actually happening?
> Error:
> An uncaught Exception occurred on "main" thread.
> Calling js method onCreateView failed
> Error: java.lang.NullPointerException
> android.widget.TextView.setTextColor(TextView.java:4309)
> com.tns.Runtime.callJSMethodNative(Native Method)
> com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1209)
> com.tns.Runtime.callJSMethodImpl(Runtime.java:1096)
> com.tns.Runtime.callJSMethod(Runtime.java:1083)
> com.tns.Runtime.callJSMethod(Runtime.java:1063)
> com.tns.Runtime.callJSMethod(Runtime.java:1055)
> com.tns.FragmentClass.onCreateView(FragmentClass.java:53)
> androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
> androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
> androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
> androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
> androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
> androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
> androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
> androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
> androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
> androidx.fragment.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
> android.os.Handler.handleCallback(Handler.java:873)
> android.os.Handler.dispatchMessage(Handler.java:99)
> android.os.Looper.loop(Looper.java:193)
> android.app.ActivityThread.main(ActivityThread.java:6703)
> java.lang.reflect.Method.invoke(Native Method)
> com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
> 
> StackTrace:
> TextBase.(file:///data/data/org.nativescript.projectname/files/app/vendor.js:74190:38)
> at applyAllNativeSetters(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50385:31)
> at initNativeView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50289:5)
> at ViewBase.onResumeNativeUpdates(file:///data/data/org.nativescript.projectname/files/app/vendor.js:51401:18)
> at ViewBase._resumeNativeUpdates(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50932:12)
> at ViewBase.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50878:10)
> at View.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:53296:31)
> at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50981:20)
> at ViewBase.callFunctionWithSuper(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50970:5)
> at ViewBase.callLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50980:10)
> at ViewBase.loadView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:51157:12)
> at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50881:13)
> at LayoutBaseCommon.eachChildView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:62391:20)
> at ViewCommon.eachChild(file:///data/data/org.nativescript.projectname/files/app/vendor.js:52759:10)
> at ViewBase.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50880:10)
> at View.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:53296:31)
> at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50981:20)
> at ViewBase.callFunctionWithSuper(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50970:5)
> at ViewBase.callLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50980:10)
> at ViewBase.loadView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:51157:12)
> at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50881:13)
> at LayoutBaseCommon.eachChildView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:62391:20)
> at ViewCommon.eachChild(file:///data/data/org.nativescript.projectname/files/app/vendor.js:52759:10)
> at ViewBase.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50880:10)
> at View.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:53296:31)
> at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50981:20)
> at ViewBase.callFunctionWithSuper(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50970:5)
> at ViewBase.callLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50980:10)
> at ViewBase.loadView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:51157:12)
> at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50881:13)
> at LayoutBaseCommon.eachChildView(file:///data/data/org.nativescript.projectname/files/app/vendor.js:62391:20)
> at ViewCommon.eachChild(file:///data/data/org.nativescript.projectname/files/app/vendor.js:52759:10)
> at ViewBase.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50880:10)
> at View.onLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:53296:31)
> at (file:///data/data/org.nativescript.projectname/files/app/vendor.js:50981:20)
> at ViewBase.callFunctionWithSuper(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50970:5)
> at ViewBase.callLoaded(file:///data/data/org.nativescript.projectname/files/app/vendor.js:50980:10)
> ... 24 more
> 
> When the app start the splash screen is visible for some seconds, then it crash.
> 'tns doctor' don't detect any issues.

Try to comment on different page components' main page components to detect which one causes the issue. 

If my memory serves, I had problems with the Carousel plugin try to update its version.
