### ISSUE TITLE
NativeScriptActivity not found. But only on one dev machine.

### ISSUE THREAD

**Issue by thelonecabbage** [nativescript-vue/nativescript-vue#574]
### Version
2.4.0

### Reproduction link
proprietary repo
### Platform and OS info
Linux Ubuntu 16.04LTS

### Steps to reproduce
```
rm -rf node_modules/  platforms/ hooks/
tns debug android
```

### What is expected?
to load the first screen of the app on the device or emulator

### What is actually happening?
```
Project successfully prepared (android)
Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Successfully transferred bundle.js on device emulator-5554.
Successfully transferred runtime.js on device emulator-5554.
Successfully transferred vendor.js on device emulator-5554.
Restarting application on device emulator-5554...
device: emulator-5554 debug port: 40000

To start debugging, open the following URL in Chrome:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&ws=localhost:40000

Successfully synced application org.bluevine.depositapp on device emulator-5554.
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "com.tns.NativeScriptActivity" not found.
System.err: File: (/data/data/org.bluevine.depositapp/files/internal/ts_helpers.js:154:25)
System.err: 
System.err: StackTrace: 
System.err: (/data/data/org.bluevine.depositapp/files/internal/ts_helpers.js:154:26)
System.err:     at __decorate(/data/data/org.bluevine.depositapp/files/internal/ts_helpers.js:13:19)
System.err:     at (file:///node_modules/@nativescript/core/ui/frame/activity.js:49:27)
System.err:     at (file:///node_modules/@nativescript/core/ui/frame/activity.js:53:2)
System.err:     at ../node_modules/@nativescript/core/ui/frame/activity.js(file:///data/data/org.bluevine.depositapp/files/app/vendor.js:25286:30)
System.err:     at __webpack_require__(file:///app/webpack/bootstrap:750:0)
System.err:     at fn(file:///app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/tns-core-modules/ui/frame/activity.js(file:///node_modules/tns-core-modules/ui/frame/activity.js:7:9)
System.err:     at __webpack_require__(file:///app/webpack/bootstrap:750:0)
System.err:     at fn(file:///app/webpack/bootstrap:120:0)
System.err:     at (file:///app/app.js:5:0)
System.err:     at ./app.js(file:///data/data/org.bluevine.depositapp/files/app/bundle.js:3950:30)
System.err:     at __webpack_require__(file:///app/webpack/bootstrap:750:0)
System.err:     at checkDeferredModules(file:///app/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file:///app/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/org.bluevine.depositapp/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
System.err: 
System.err: 
System.err: Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "com.tns.NativeScriptActivity" not found.
System.err: 
System.err: StackTrace:
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: Error: com.tns.system.classes.loading.LookedUpClassNotFound: Class "com.tns.NativeScriptActivity" not found.
System.err: File: (/data/data/org.bluevine.depositapp/files/internal/ts_helpers.js:154:25)
System.err: 
System.err: StackTrace: 
System.err: (/data/data/org.bluevine.depositapp/files/internal/ts_helpers.js:154:26)
System.err:     at __decorate(/data/data/org.bluevine.depositapp/files/internal/ts_helpers.js:13:19)
System.err:     at (file:///node_modules/@nativescript/core/ui/frame/activity.js:49:27)
System.err:     at (file:///node_modules/@nativescript/core/ui/frame/activity.js:53:2)
System.err:     at ../node_modules/@nativescript/core/ui/frame/activity.js(file:///data/data/org.bluevine.depositapp/files/app/vendor.js:25286:30)
System.err:     at __webpack_require__(file:///app/webpack/bootstrap:750:0)
System.err:     at fn(file:///app/webpack/bootstrap:120:0)
System.err:     at ../node_modules/tns-core-modules/ui/frame/activity.js(file:///node_modules/tns-core-modules/ui/frame/activity.js:7:9)
System.err:     at __webpack_require__(file:///app/webpack/bootstrap:750:0)
System.err:     at fn(file:///app/webpack/bootstrap:120:0)
System.err:     at (file:///app/app.js:5:0)
System.err:     at ./app.js(file:///data/data/org.bluevine.depositapp/files/app/bundle.js:3950:30)
System.err:     at __webpack_require__(file:///app/webpack/bootstrap:750:0)
System.err:     at checkDeferredModules(file:///app/webpack/bootstrap:43:0)
System.err:     at webpackJsonpCallback(file:///app/webpack/bootstrap:30:0)
System.err:     at (file:///data/data/org.bluevine.depositapp/files/app/bundle.js:2:57)
System.err:     at require(:1:266)
```

---
It worked previously, but now it fails consistently on one dev machine (Ubuntu 16.04).   
But all other dev machines (OSX & Windows) continue to work.

My versions are:
```
    "tns-android": {
      "version": "6.1.2"
    },
    "tns-ios": {
      "version": "6.1.0"
    }
tns --version
6.2.0

```

**Comment by thelonecabbage** [comment]
I'm also running node 12.11.1

**Comment by thelonecabbage** [comment]
It worked for 1 day inside of a docker... and now it's broken again... restarting the docker does not appear to help.
