### ISSUE TITLE
OnTouch error trying to Get X and Y

### ISSUE THREAD

**Issue by hyphestos** [nativescript-vue/nativescript-vue#641]
### Version
2.6.1

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=Xg7jdt](https://play.nativescript.org/?template=play-vue&id=Xg7jdt)
### Platform and OS info
Android 9 - MIUI 11.0.3, Nativescript-Vue 2.6.10, Windows 10

### Steps to reproduce
I have added a @touch event listener on Label element like below:
<Label class="placeholder" :text="message" @touch="onTouch"></Label>

and it is linked to the following function

methods: { onTouch(arg) { console.log(arg);  } }

When running the application without the 'args' argument e.x. onTouch() { } it works fine. But when i enter the args in order to get the coordinates of the touched location i receive the following error.

LOG from device Redmi johny: [Vue warn]: Error in v-on handler: "Error: java.lang.NoSuchFieldError: no "I" field "CLASSIFICATION_AMBIGUOUS_GESTURE" in class "Landroid/view/MotionEvent;" or its superclasses"
LOG from device Redmi johny: An uncaught Exception occurred on "main" thread.
Calling js method onTouch failed
Error: java.lang.NoSuchFieldError: no "I" field "CLASSIFICATION_AMBIGUOUS_GESTURE" in class "Landroid/view/MotionEvent;" or its superclasses

More info can be fund when running the example in the playground.

### What is expected?
I am trying to get the X and Y coordinates from a touch event

### What is actually happening?
An error occurs described above

**Comment by rigor789** [comment]
I just tested the playground on `MIUI 11.0.9` and it works there. Could you perhaps share a stack-trace of the error?

**Comment by hyphestos** [comment]
Of cource.. the stacktrace is the following:

An uncaught Exception occurred on "main" thread.
Calling js method onTouch failed
Error: java.lang.NoSuchFieldError: no "I" field "CLASSIFICATION_AMBIGUOUS_GESTURE" in class "Landroid/view/MotionEvent;" or its superclasses

StackTrace:
formatProperty(file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:1404:24)
	at (file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:1393:14)
	at arrayMap(file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:20:29)
	at formatValue(file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:1392:14)
	at formatProperty(file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:1427:15)
	at (file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:1393:14)
	at arrayMap(file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:20:29)
	at formatValue(file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:1392:14)
	at formatProperty(file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:1427:15)
	at (file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:1393:14)
	at arrayMap(file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:20:29)
	at formatValue(file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:1392:14)
	at inspect(file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:1160:10)
	at (file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:14302:16)
	at (file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:14301:49)
	at onTouch(file:///data/data/org.nativescript.preview/files/app/components/HelloWorld.js:35:15)
	at invokeWithErrorHandling(file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:3368:26)
	at invoker(file:///data/data/org.nativescript.preview/files/app/tns_modules/nativescript-vue/dist/index.js:4032:14)
	at _executeCallback(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/gestures/gestures.js:330:27)
	at GesturesObserver.androidOnTouchEvent(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/gestures/gestures.js:250:13)
	at (file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view/view.js:275:25)
	at View.handleGestureTouch(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view/view.js:274:18)
	at TouchListenerImpl.onTouch(file:///data/data/org.nativescript.preview/files/app/tns_modules/@nativescript/core/ui/core/view/view.js:41:19)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at com.tns.gen.java.lang.Object_view_32_32_TouchListenerImpl.onTouch(Object_view_32_32_TouchListenerImpl.java:19)
	at android.view.View.dispatchTouchEvent(View.java:12523)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:444)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1835)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3465)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:402)
	at android.view.View.dispatchPointerEvent(View.java:12768)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5285)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5085)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4600)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4653)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4619)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4759)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4627)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4816)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4600)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4653)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4619)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4627)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4600)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7328)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7297)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7258)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7434)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:247)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.NoSuchFieldError: no "I" field "CLASSIFICATION_AMBIGUOUS_GESTURE" in class "Landroid/view/MotionEvent;" or its superclasses
	... 57 more

**Comment by rigor789** [comment]
Ah - seems like you are running 2.5.1 - and the crash is likely caused by the `console.log` override that pretty-formats the output.

Try logging just the values, and it should work fine: `console.log(args.getX());`

**Comment by hyphestos** [comment]
Seems to be working.. Thank you very much for your help!
