### ISSUE TITLE
App crashes after installing RadDataForm and trying to import it into  app.js

### ISSUE THREAD

**Issue by hraynaud** [nativescript-vue/nativescript-vue#698]
### Version
2.7.1

### Reproduction link
[https://github.com/hraynaud/test-ns-app](https://github.com/hraynaud/test-ns-app)
### Platform and OS info
IOS 10.15

### Steps to reproduce
install the RadDataForm according to the instructions here: https://docs.nativescript.org/vuejs/ns-ui/dataform/getting-started.

Modify my main.js (in my case app.js) to import RadDataForm as per the instructions.

start the application by executing: 
tns run ios  --device 'iPhone 11' --env.development

### What is expected?
The application starts as normal

### What is actually happening?
The application crashes with the following stack trace: 

***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x105c9e83e NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x105cf06c4 -[TNSRuntime executeModule:referredBy:]
3   0x10559f1b3 main
4   0x7fff520ce1fd start
JavaScript stack trace:
../node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js(file:///node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js:59:59)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at ../node_modules/nativescript-ui-autocomplete/ui-autocomplete.js(file:///node_modules/nativescript-ui-autocomplete/ui-autocomplete.js:1:0)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at ../node_modules/nativescript-ui-dataform/ui-dataform.common.js(file:///node_modules/nativescript-ui-dataform/ui-dataform.common.js:1:0)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at ../node_modules/nativescript-ui-dataform/ui-dataform.js(file:///node_modules/nativescript-ui-dataform/ui-dataform.js:1:0)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at ../node_modules/nativescript-ui-dataform/vue/index.js(file:///node_modules/nativescript-ui-dataform/vue/index.js:1:0)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at file:///app/app.js:1:0
at ./app.js(file:///app/bundle.js:4244:34)
<…>
JavaScript error:
file:///node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js:59:59: JS ERROR TypeError: undefined is not a constructor (evaluating 'new _nativescript_core__WEBPACK_IMPORTED_MODULE_0__["Property"]')
(CoreFoundation) *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: undefined is not a constructor (evaluating 'new _nativescript_core__WEBPACK_IMPORTED_MODULE_0__["Property"]')
at
../node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js(file:///node_modules/nativescript-ui-autocomplete/ui-autocomplete.common.js:59:59)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at ../node_modules/nativescript-ui-autocomplete/ui-autocomplete.js(file:///node_modules/nativescript-ui-autocomplete/ui-autocomplete.js:1:0)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at ../node_modules/nativescript-ui-dataform/ui-dataform.common.js(file:///node_modules/nativescript-ui-dataform/ui-dataform.common.js:1:0)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at ../node_modules/nativescript-ui-dataform/ui-dataform.js(file:///node_modules/nativescript-ui-dataform/ui-dataform.js:1:0)
at __webpack_require__(file:///app/webpack/bootstrap:750:0)
at fn(file:///app/webpack/bootstrap:120:0)
at ../node_modules/nativescript-ui-dataform/<…>
NativeScript caught signal 6.
Native Stack:
1   0x105cef321 sig_handler(int)
2   0x7fff522ab5fd _sigtramp
3   0x7fff5219ff39 itoa64
4   0x7fff5219bb7c abort
5   0x7fff500a2858 abort_message
6   0x7fff50093cbf demangling_unexpected_handler()
7   0x7fff51253c0b _objc_terminate()
8   0x7fff500a1c87 std::__terminate(void (*)())
9   0x7fff500a440b __cxa_get_exception_ptr
10  0x7fff500a43d2 __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
11  0x7fff51253ad6 _objc_exception_destructor(void*)
12  0x105c9ed7f NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x105cf06c4 -[TNSRuntime executeModule:referredBy:]
14  0x10559f1b3 main
15  0x7fff520ce1fd start
JS Stack:

**Comment by hraynaud** [comment]
I've updated the link to point to a repo with a freshly generated test app.

**Comment by hraynaud** [comment]
downgrading to v6.1.0 solved the problem for me. Apparently the latest and greatest has code designed to run under nativescript V7 but that is incompatible with the version of NS I"m running with is 6x
