### ISSUE TITLE
"parameter must be a descendant of this view" error

### ISSUE THREAD

**Issue by zThundy** [nativescript-vue/nativescript-vue#914]
### Version
2.9.0

### Reproduction link
[https://play.nativescript.org/?template=play-vue&id=aShcgF&v=2](https://play.nativescript.org/?template=play-vue&id=aShcgF&v=2)
### Platform and OS info
Android

### Steps to reproduce
Open the Account TabView
Click on the Register Button
Go Back
Scroll in the Event or Homepage tab

### What is expected?
Go back from the nested account tabs and keep using the app as logged in or registered

### What is actually happening?
The app crashes with the error
"parameter must be a descendant of this view"

### Additional comments
I'm fearly new to the world of developing apps, and i managed to find nativescript and started using it. I'm not experienced enough to manage this issue by myself, so i'm asking here if anyone has the same problem or knows how to solve it.

**Comment by rigor789** [comment]
Is there any more to the error message? A stack trace perhaps?

**Comment by zThundy** [comment]
Yes sorry. Though it was not important

```
An uncaught Exception occurred on "main" thread.
parameter must be a descendant of this view

StackTrace:
java.lang.IllegalArgumentException: parameter must be a descendant of this view
 at android.view.ViewGroup.offsetRectBetweenParentAndChild(ViewGroup.java:6153)
 at android.view.ViewGroup.offsetDescendantRectToMyCoords(ViewGroup.java:6075)
 at android.view.ViewGroup$ViewLocationHolder.init(ViewGroup.java:8800)
 at android.view.ViewGroup$ViewLocationHolder.obtain(ViewGroup.java:8734)
 at android.view.ViewGroup$ChildListForAccessibility.init(ViewGroup.java:8669)
 at android.view.ViewGroup$ChildListForAccessibility.obtain(ViewGroup.java:8641)
 at android.view.ViewGroup.addChildrenForAccessibility(ViewGroup.java:2344)
 at android.view.ViewGroup.onInitializeAccessibilityNodeInfoInternal(ViewGroup.java:3749)
 at android.view.View$AccessibilityDelegate.onInitializeAccessibilityNodeInfo(View.java:27320)
 at androidx.core.view.AccessibilityDelegateCompat.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:275)
 at androidx.viewpager.widget.ViewPager$MyAccessibilityDelegate.onInitializeAccessibilityNodeInfo(ViewPager.java:3053)
 at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityNodeInfo(AccessibilityDelegateCompat.java:86)
 at android.view.View.onInitializeAccessibilityNodeInfo(View.java:7960)
 at android.view.View.createAccessibilityNodeInfoInternal(View.java:7921)
 at android.view.View$AccessibilityDelegate.createAccessibilityNodeInfo(View.java:27418)
 at android.view.View.createAccessibilityNodeInfo(View.java:7904)
 at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:146)
 at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
 at android.view.View.onInitializeAccessibilityEventInternal(View.java:7858)
 at android.view.View$AccessibilityDelegate.onInitializeAccessibilityEvent(View.java:27301)
 at androidx.core.view.AccessibilityDelegateCompat.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:256)
 at androidx.viewpager.widget.ViewPager$MyAccessibilityDelegate.onInitializeAccessibilityEvent(ViewPager.java:3041)
 at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.onInitializeAccessibilityEvent(AccessibilityDelegateCompat.java:76)
 at android.view.View.onInitializeAccessibilityEvent(View.java:7844)
 at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:7708)
 at android.view.View$AccessibilityDelegate.sendAccessibilityEventUnchecked(View.java:27240)
 at androidx.core.view.AccessibilityDelegateCompat.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:195)
 at androidx.core.view.AccessibilityDelegateCompat$AccessibilityDelegateAdapter.sendAccessibilityEventUnchecked(AccessibilityDelegateCompat.java:112)
 at android.view.View.sendAccessibilityEventUnchecked(View.java:7691)
 at android.view.ViewRootImpl$SendWindowContentChangedAccessibilityEvent.run(ViewRootImpl.java:9304)
 at android.os.Handler.handleCallback(Handler.java:789)
 at android.os.Handler.dispatchMessage(Handler.java:98)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6944)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by zThundy** [comment]
Update: I fixed it by wrapping the account TabView inside another Frama (as the docs said. I'm dumb :D) Thank for the support and great work on nativescript-vue! ;D

**Comment by rigor789** [comment]
Oh cool, thanks for the update - I was looking around to see similar issues, as frankly have never seen that one, and found nothing...

**Comment by zThundy** [comment]
Also i'm now supporting you on patreon :)

**Comment by zThundy** [comment]
For anyone needing any more informations, here's some code examples:

This is a TabView wich i use in the main application frame
```
...
<TabViewItem title="Account">
    <!-- This will be useful in future if i need to implement the -->
    <!-- transitions between elements -->
    <Frame id="account" ref="account">
        <Page actionBarHidden="true">
            <Account />
        </Page>
    </Frame>
</TabViewItem>
...
```

Then for the transition i use this function call in method (cause i use buttons to navigate in the account page)
```
this.$navigateTo(<Component>, {
    ...
    frame: "account"
})
```

So the transition will happen in the upper frame defined in the main page and not on the default frame.

**Comment by rigor789** [comment]
Thanks!
